# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class CloudtrailAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :s3_bucket_name, T::String
    attribute? :advanced_event_selector, T::Array.of(T::Hash).optional
    attribute? :cloud_watch_logs_group_arn, T::String.optional
    attribute? :cloud_watch_logs_role_arn, T::String.optional
    attribute? :enable_log_file_validation, T::Bool.optional
    attribute? :enable_logging, T::Bool.optional
    attribute? :event_selector, T::Array.of(T::Hash).optional
    attribute? :include_global_service_events, T::Bool.optional
    attribute? :insight_selector, T::Array.of(T::Hash).optional
    attribute? :is_multi_region_trail, T::Bool.optional
    attribute? :is_organization_trail, T::Bool.optional
    attribute? :kms_key_id, T::String.optional
    attribute? :s3_key_prefix, T::String.optional
    attribute? :sns_topic_name, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
