# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_autoscaling_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSAutoscalingAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_autoscaling_attachment,
      attributes_class: AWS::Types::AutoscalingAttachmentAttributes,
      outputs: { id: :id },
      map: [:autoscaling_group_name],
      map_present: [:elb, :lb_target_group_arn]
  end
  module AWS
    include AWSAutoscalingAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
