# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class NetworkmanagerTransitGatewayConnectPeerAssociationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :device_id, T::String
    attribute :global_network_id, T::String
    attribute :transit_gateway_connect_peer_arn, T::String
    attribute? :link_id, T::String.optional
  end
end
