# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class SagemakerDeviceFleetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :device_fleet_name, T::String
    attribute :output_config, T::Hash
    attribute :role_arn, T::String
    attribute? :description, T::String.optional
    attribute? :enable_iot_role_alias, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
