# Code generated by pangea-forge.
# InSpec profile for verifying aws_notifications_organizational_unit_association infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_notifications_organizational_unit_association/ -t aws://

control 'aws_notifications_organizational_unit_association-exists' do
  impact 1.0
  title 'Manages a aws_notifications_organizational_unit_association resource'
  desc 'Verify that the aws_notifications_organizational_unit_association resource exists and has expected properties'

  describe aws_notifications_organizational_unit_association(name: attribute('id')) do
    it { should exist }
    its('notification_configuration_arn') { should_not be_nil }
    its('organizational_unit_id') { should_not be_nil }
  end
end
