# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_macie2_custom_data_identifier/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSMacie2CustomDataIdentifier
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_macie2_custom_data_identifier,
      attributes_class: AWS::Types::Macie2CustomDataIdentifierAttributes,
      outputs: { id: :id },
      map_present: [:description, :ignore_words, :keywords, :maximum_match_distance, :name, :name_prefix, :regex, :region, :tags, :tags_all]
  end
  module AWS
    include AWSMacie2CustomDataIdentifier
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
