# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class IamRolePolicyAttachmentsExclusiveAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :policy_arns, T::Array.of(T::String)
    attribute :role_name, T::String
  end
end
