# Code generated by pangea-forge.
# InSpec profile for verifying aws_datasync_location_efs infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_datasync_location_efs/ -t aws://

control 'aws_datasync_location_efs-exists' do
  impact 1.0
  title 'Manages a aws_datasync_location_efs resource'
  desc 'Verify that the aws_datasync_location_efs resource exists and has expected properties'

  describe aws_datasync_location_efs(name: attribute('id')) do
    it { should exist }
    its('ec2_config') { should_not be_nil }
    its('efs_file_system_arn') { should_not be_nil }
  end
end
