# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class FinspaceKxDataviewAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :auto_update, T::Bool
    attribute :az_mode, T::String
    attribute :database_name, T::String
    attribute :environment_id, T::String
    attribute :name, T::String
    attribute? :availability_zone_id, T::String.optional
    attribute? :changeset_id, T::String.optional
    attribute? :description, T::String.optional
    attribute? :read_write, T::Bool.optional
    attribute? :segment_configurations, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
  end
end
