# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class VpcEndpointServiceAllowedPrincipalAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :principal_arn, T::String
    attribute :vpc_endpoint_service_id, T::String
    attribute? :region, T::String.optional
  end
end
