# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_api_gateway_integration_response/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSApiGatewayIntegrationResponse
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_api_gateway_integration_response,
      attributes_class: AWS::Types::ApiGatewayIntegrationResponseAttributes,
      outputs: { id: :id },
      map: [:http_method, :resource_id, :rest_api_id, :status_code],
      map_present: [:content_handling, :region, :response_parameters, :response_templates, :selection_pattern]
  end
  module AWS
    include AWSApiGatewayIntegrationResponse
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
