# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_datazone_asset_type/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSDatazoneAssetType
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_datazone_asset_type,
      attributes_class: AWS::Types::DatazoneAssetTypeAttributes,
      outputs: { id: :id },
      map: [:domain_identifier, :name, :owning_project_identifier],
      map_present: [:description, :forms_input]
  end
  module AWS
    include AWSDatazoneAssetType
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
