# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class S3BucketLoggingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :bucket, T::String
    attribute :target_bucket, T::String
    attribute :target_prefix, T::String
    attribute? :expected_bucket_owner, T::String.optional
    attribute? :target_grant, T::Array.of(T::Hash).optional
    attribute? :target_object_key_format, T::Hash.optional
  end
end
