# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class BedrockagentcoreAgentRuntimeEndpointAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :agent_runtime_id, T::String
    attribute :name, T::String
    attribute? :agent_runtime_version, T::String.optional
    attribute? :description, T::String.optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
