# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RouteTableAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :vpc_id, T::String
    attribute? :propagating_vgws, T::Array.of(T::String).optional
    attribute? :route, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
