# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_iam_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSIamGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_iam_group,
      attributes_class: AWS::Types::IamGroupAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:path]
  end
  module AWS
    include AWSIamGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
