# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_devicefarm_network_profile/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSDevicefarmNetworkProfile
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_devicefarm_network_profile,
      attributes_class: AWS::Types::DevicefarmNetworkProfileAttributes,
      outputs: { id: :id },
      map: [:name, :project_arn],
      map_present: [:description, :downlink_bandwidth_bits, :downlink_delay_ms, :downlink_jitter_ms, :downlink_loss_percent, :tags, :tags_all, :type, :uplink_bandwidth_bits, :uplink_delay_ms, :uplink_jitter_ms, :uplink_loss_percent]
  end
  module AWS
    include AWSDevicefarmNetworkProfile
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
