# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_storagegateway_upload_buffer/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSStoragegatewayUploadBuffer
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_storagegateway_upload_buffer,
      attributes_class: AWS::Types::StoragegatewayUploadBufferAttributes,
      outputs: { id: :id },
      map: [:gateway_arn],
      map_present: [:disk_id, :disk_path, :region]
  end
  module AWS
    include AWSStoragegatewayUploadBuffer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
