# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_cloudfront_multitenant_distribution/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSCloudfrontMultitenantDistribution
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_cloudfront_multitenant_distribution,
      attributes_class: AWS::Types::CloudfrontMultitenantDistributionAttributes,
      outputs: { id: :id },
      map: [:comment],
      map_present: [:active_trusted_key_groups, :cache_behavior, :custom_error_response, :default_cache_behavior, :default_root_object, :http_version, :origin, :origin_group, :restrictions, :tags, :tenant_config, :viewer_certificate, :web_acl_id],
      map_bool: [:enabled]
  end
  module AWS
    include AWSCloudfrontMultitenantDistribution
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
