# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_db_proxy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSDbProxy
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_db_proxy,
      attributes_class: AWS::Types::DbProxyAttributes,
      outputs: { id: :id },
      map: [:engine_family, :name, :role_arn, :vpc_subnet_ids],
      map_present: [:auth, :default_auth_scheme, :endpoint_network_type, :idle_client_timeout, :region, :tags, :tags_all, :target_connection_network_type, :vpc_security_group_ids],
      map_bool: [:debug_logging, :require_tls]
  end
  module AWS
    include AWSDbProxy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
