# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class DbProxyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :auth, T::Array.of(T::Hash)
    attribute :engine_family, T::String
    attribute :name, T::String
    attribute :role_arn, T::String
    attribute :vpc_subnet_ids, T::Array.of(T::String)
    attribute? :debug_logging, T::Bool.optional
    attribute? :idle_client_timeout, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :require_tls, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
    attribute? :vpc_security_group_ids, T::Array.of(T::String).optional
  end
end
