# Code generated by pangea-forge.
# InSpec profile for verifying aws_sesv2_dedicated_ip_pool infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_sesv2_dedicated_ip_pool/ -t aws://

control 'aws_sesv2_dedicated_ip_pool-exists' do
  impact 1.0
  title 'Manages a aws_sesv2_dedicated_ip_pool resource'
  desc 'Verify that the aws_sesv2_dedicated_ip_pool resource exists and has expected properties'

  describe aws_sesv2_dedicated_ip_pool(name: attribute('id')) do
    it { should exist }
    its('pool_name') { should_not be_nil }
  end
end
