# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class CloudfrontOriginAccessControlAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :origin_access_control_origin_type, T::String
    attribute :signing_behavior, T::String
    attribute :signing_protocol, T::String
    attribute? :description, T::String.optional
  end
end
