# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_appintegrations_event_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSAppintegrationsEventIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_appintegrations_event_integration,
      attributes_class: AWS::Types::AppintegrationsEventIntegrationAttributes,
      outputs: { id: :id },
      map: [:event_filter, :eventbridge_bus, :name],
      map_present: [:description, :region, :tags, :tags_all]
  end
  module AWS
    include AWSAppintegrationsEventIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
