# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class SsmPatchBaselineAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute? :approval_rule, T::Array.of(T::Hash).optional
    attribute? :approved_patches, T::Array.of(T::String).optional
    attribute? :approved_patches_compliance_level, T::String.optional
    attribute? :approved_patches_enable_non_security, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :global_filter, T::Array.of(T::Hash).optional
    attribute? :operating_system, T::String.optional
    attribute? :rejected_patches, T::Array.of(T::String).optional
    attribute? :source, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
  end
end
