# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class GuarddutyFilterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :action, T::String
    attribute :detector_id, T::String
    attribute :finding_criteria, T::Hash
    attribute :name, T::String
    attribute :rank, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :description, T::String.optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
