# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class VpcEndpointServicePrivateDnsVerificationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :service_id, T::String
    attribute? :wait_for_verification, T::Bool.optional
  end
end
