# Code generated by pangea-forge.
# InSpec profile for verifying aws_medialive_channel infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_medialive_channel/ -t aws://

control 'aws_medialive_channel-exists' do
  impact 1.0
  title 'Manages a aws_medialive_channel resource'
  desc 'Verify that the aws_medialive_channel resource exists and has expected properties'

  describe aws_medialive_channel(name: attribute('id')) do
    it { should exist }
    its('channel_class') { should_not be_nil }
    its('destinations') { should_not be_nil }
    its('encoder_settings') { should_not be_nil }
    its('input_attachments') { should_not be_nil }
    its('input_specification') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
