# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_ec2_client_vpn_network_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSEc2ClientVpnNetworkAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_ec2_client_vpn_network_association,
      attributes_class: AWS::Types::Ec2ClientVpnNetworkAssociationAttributes,
      outputs: { id: :id },
      map: [:client_vpn_endpoint_id, :subnet_id]
  end
  module AWS
    include AWSEc2ClientVpnNetworkAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
