# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class EksClusterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :role_arn, T::String
    attribute :vpc_config, T::Hash
    attribute? :access_config, T::Hash.optional
    attribute? :bootstrap_self_managed_addons, T::Bool.optional
    attribute? :compute_config, T::Hash.optional
    attribute? :control_plane_scaling_config, T::Hash.optional
    attribute? :deletion_protection, T::Bool.optional
    attribute? :enabled_cluster_log_types, T::Array.of(T::String).optional
    attribute? :encryption_config, T::Hash.optional
    attribute? :force_update_version, T::Bool.optional
    attribute? :kubernetes_network_config, T::Hash.optional
    attribute? :outpost_config, T::Hash.optional
    attribute? :region, T::String.optional
    attribute? :remote_network_config, T::Hash.optional
    attribute? :storage_config, T::Hash.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
    attribute? :upgrade_policy, T::Hash.optional
    attribute? :version, T::String.optional
    attribute? :zonal_shift_config, T::Hash.optional
  end
end
