# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_grafana_workspace_api_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSGrafanaWorkspaceApiKey
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_grafana_workspace_api_key,
      attributes_class: AWS::Types::GrafanaWorkspaceApiKeyAttributes,
      outputs: { id: :id },
      map: [:key_name, :key_role, :seconds_to_live, :workspace_id]
  end
  module AWS
    include AWSGrafanaWorkspaceApiKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
