# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_ec2_subnet_cidr_reservation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSEc2SubnetCidrReservation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_ec2_subnet_cidr_reservation,
      attributes_class: AWS::Types::Ec2SubnetCidrReservationAttributes,
      outputs: { id: :id },
      map: [:cidr_block, :reservation_type, :subnet_id],
      map_present: [:description]
  end
  module AWS
    include AWSEc2SubnetCidrReservation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
