# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class PrometheusWorkspaceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute? :alias, T::String.optional
    attribute? :kms_key_arn, T::String.optional
    attribute? :logging_configuration, T::Hash.optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
