# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_rds_instance_state/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSRdsInstanceState
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_rds_instance_state,
      attributes_class: AWS::Types::RdsInstanceStateAttributes,
      outputs: { id: :id },
      map: [:identifier, :state]
  end
  module AWS
    include AWSRdsInstanceState
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
