# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_s3control_access_grants_instance/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSS3controlAccessGrantsInstance
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_s3control_access_grants_instance,
      attributes_class: AWS::Types::S3controlAccessGrantsInstanceAttributes,
      outputs: { id: :id },
      map_present: [:identity_center_arn, :tags]
  end
  module AWS
    include AWSS3controlAccessGrantsInstance
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
