# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class SagemakerCodeRepositoryAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :code_repository_name, T::String
    attribute :git_config, T::Array.of(T::Hash)
    attribute? :tags, T::Hash.optional
  end
end
