# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class ApiGatewayResourceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :parent_id, T::String
    attribute :path_part, T::String
    attribute :rest_api_id, T::String
    attribute? :region, T::String.optional
  end
end
