# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RdsIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :integration_name, T::String
    attribute :source_arn, T::String
    attribute :target_arn, T::String
    attribute? :additional_encryption_context, T::Hash.optional
    attribute? :data_filter, T::String.optional
    attribute? :kms_key_id, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
