# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class Ec2ClientVpnEndpointAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :authentication_options, T::Array.of(T::Hash)
    attribute :client_cidr_block, T::String
    attribute :connection_log_options, T::Array.of(T::Hash)
    attribute :server_certificate_arn, T::String
    attribute? :client_connect_options, T::Array.of(T::Hash).optional
    attribute? :client_login_banner_options, T::Array.of(T::Hash).optional
    attribute? :client_route_enforcement_options, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :dns_servers, T::Array.of(T::String).optional
    attribute? :self_service_portal, T::String.optional
    attribute? :session_timeout_hours, T::Float.optional
    attribute? :split_tunnel, T::Bool.optional
    attribute? :tags, T::Hash.optional
    attribute? :transport_protocol, T::String.optional
    attribute? :vpn_port, T::Float.optional
  end
end
