# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RedshiftserverlessCustomDomainAssociationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :custom_domain_certificate_arn, T::String
    attribute :custom_domain_name, T::String
    attribute :workgroup_name, T::String
  end
end
