# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_directory_service_radius_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSDirectoryServiceRadiusSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_directory_service_radius_settings,
      attributes_class: AWS::Types::DirectoryServiceRadiusSettingsAttributes,
      outputs: { id: :id },
      map: [:authentication_protocol, :directory_id, :display_label, :radius_port, :radius_retries, :radius_servers, :radius_timeout, :shared_secret],
      map_bool: [:use_same_username]
  end
  module AWS
    include AWSDirectoryServiceRadiusSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
