# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_connect_bot_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSConnectBotAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_connect_bot_association,
      attributes_class: AWS::Types::ConnectBotAssociationAttributes,
      outputs: { id: :id },
      map: [:instance_id, :lex_bot]
  end
  module AWS
    include AWSConnectBotAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
