# Code generated by pangea-forge.
# InSpec profile for verifying aws_service_discovery_instance infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_service_discovery_instance/ -t aws://

control 'aws_service_discovery_instance-exists' do
  impact 1.0
  title 'Manages a aws_service_discovery_instance resource'
  desc 'Verify that the aws_service_discovery_instance resource exists and has expected properties'

  describe aws_service_discovery_instance(name: attribute('id')) do
    it { should exist }
    its('attributes') { should_not be_nil }
    its('instance_id') { should_not be_nil }
    its('service_id') { should_not be_nil }
  end
end
