# Code generated by pangea-forge.
# InSpec profile for verifying aws_acmpca_permission infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_acmpca_permission/ -t aws://

control 'aws_acmpca_permission-exists' do
  impact 1.0
  title 'Manages a aws_acmpca_permission resource'
  desc 'Verify that the aws_acmpca_permission resource exists and has expected properties'

  describe aws_acmpca_permission(name: attribute('id')) do
    it { should exist }
    its('actions') { should_not be_nil }
    its('certificate_authority_arn') { should_not be_nil }
    its('principal') { should_not be_nil }
  end
end
