# Code generated by pangea-forge.
# InSpec profile for verifying aws_route53_vpc_association_authorization infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_route53_vpc_association_authorization/ -t aws://

control 'aws_route53_vpc_association_authorization-exists' do
  impact 1.0
  title 'Manages a aws_route53_vpc_association_authorization resource'
  desc 'Verify that the aws_route53_vpc_association_authorization resource exists and has expected properties'

  describe aws_route53_vpc_association_authorization(name: attribute('id')) do
    it { should exist }
    its('vpc_id') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
