# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class ApiGatewayRestApiAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute? :body, T::String.optional
    attribute? :endpoint_configuration, T::Array.of(T::Hash).optional
    attribute? :fail_on_warnings, T::Bool.optional
    attribute? :parameters, T::Hash.optional
    attribute? :put_rest_api_mode, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
