# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_dx_gateway_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSDxGatewayAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_dx_gateway_association,
      attributes_class: AWS::Types::DxGatewayAssociationAttributes,
      outputs: { id: :id },
      map: [:dx_gateway_id],
      map_present: [:proposal_id, :vpn_gateway_id]
  end
  module AWS
    include AWSDxGatewayAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
