# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class S3AccessPointAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :bucket, T::String
    attribute :name, T::String
    attribute? :account_id, T::String.optional
    attribute? :bucket_account_id, T::String.optional
    attribute? :policy, (T::String | T::Hash).optional
    attribute? :public_access_block_configuration, T::Hash.optional
    attribute? :vpc_configuration, T::Hash.optional
  end
end
