# Code generated by pangea-forge.
# InSpec profile for verifying aws_devopsguru_resource_collection infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_devopsguru_resource_collection/ -t aws://

control 'aws_devopsguru_resource_collection-exists' do
  impact 1.0
  title 'Manages a aws_devopsguru_resource_collection resource'
  desc 'Verify that the aws_devopsguru_resource_collection resource exists and has expected properties'

  describe aws_devopsguru_resource_collection(name: attribute('id')) do
    it { should exist }
    its('type') { should_not be_nil }
  end
end
