# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class CeAnomalySubscriptionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :frequency, T::String
    attribute :monitor_arn_list, T::Array.of(T::String)
    attribute :name, T::String
    attribute :subscriber, T::Array.of(T::Hash)
    attribute? :tags, T::Hash.optional
    attribute? :threshold_expression, T::Array.of(T::Hash).optional
  end
end
