# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_secretsmanager_tag/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSSecretsmanagerTag
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_secretsmanager_tag,
      attributes_class: AWS::Types::SecretsmanagerTagAttributes,
      outputs: { id: :id },
      map: [:key, :secret_id, :value],
      map_present: [:region]
  end
  module AWS
    include AWSSecretsmanagerTag
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
