# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RedshiftDataShareConsumerAssociationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :data_share_arn, T::String
    attribute? :allow_writes, T::Bool.optional
    attribute? :associate_entire_account, T::Bool.optional
    attribute? :consumer_arn, T::String.optional
    attribute? :consumer_region, T::String.optional
  end
end
