# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class AuditmanagerAssessmentDelegationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :assessment_id, T::String
    attribute :control_set_id, T::String
    attribute :role_arn, T::String
    attribute :role_type, T::String
    attribute? :comment, T::String.optional
  end
end
