# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_s3tables_table_bucket_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSS3tablesTableBucketPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_s3tables_table_bucket_policy,
      attributes_class: AWS::Types::S3tablesTableBucketPolicyAttributes,
      outputs: { id: :id },
      map: [:resource_policy, :table_bucket_arn]
  end
  module AWS
    include AWSS3tablesTableBucketPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
