# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RamResourceShareAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute? :allow_external_principals, T::Bool.optional
    attribute? :permission_arns, T::Array.of(T::String).optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
