# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class FinspaceKxScalingGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :availability_zone_id, T::String
    attribute :environment_id, T::String
    attribute :host_type, T::String
    attribute :name, T::String
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
