# Code generated by pangea-forge.
# InSpec profile for verifying aws_fsx_ontap_storage_virtual_machine infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_fsx_ontap_storage_virtual_machine/ -t aws://

control 'aws_fsx_ontap_storage_virtual_machine-exists' do
  impact 1.0
  title 'Manages a aws_fsx_ontap_storage_virtual_machine resource'
  desc 'Verify that the aws_fsx_ontap_storage_virtual_machine resource exists and has expected properties'

  describe aws_fsx_ontap_storage_virtual_machine(name: attribute('id')) do
    it { should exist }
    its('file_system_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
