# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class CloudwatchEventConnectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :auth_parameters, T::Hash
    attribute :authorization_type, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :invocation_connectivity_parameters, T::Hash.optional
    attribute? :kms_key_identifier, T::String.optional
  end
end
