# Code generated by pangea-forge.
# InSpec profile for verifying aws_guardduty_organization_configuration infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_guardduty_organization_configuration/ -t aws://

control 'aws_guardduty_organization_configuration-exists' do
  impact 1.0
  title 'Manages a aws_guardduty_organization_configuration resource'
  desc 'Verify that the aws_guardduty_organization_configuration resource exists and has expected properties'

  describe aws_guardduty_organization_configuration(name: attribute('id')) do
    it { should exist }
    its('auto_enable_organization_members') { should_not be_nil }
    its('detector_id') { should_not be_nil }
  end
end
