# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class VpcNetworkPerformanceMetricSubscriptionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :destination, T::String
    attribute :source, T::String
    attribute? :metric, T::String.optional
    attribute? :region, T::String.optional
    attribute? :statistic, T::String.optional
  end
end
