# Code generated by pangea-forge.
# InSpec profile for verifying aws_sagemaker_device infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_sagemaker_device/ -t aws://

control 'aws_sagemaker_device-exists' do
  impact 1.0
  title 'Manages a aws_sagemaker_device resource'
  desc 'Verify that the aws_sagemaker_device resource exists and has expected properties'

  describe aws_sagemaker_device(name: attribute('id')) do
    it { should exist }
    its('device') { should_not be_nil }
    its('device_fleet_name') { should_not be_nil }
  end
end
