# Code generated by pangea-forge.
# InSpec profile for verifying aws_s3_bucket_policy infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_s3_bucket_policy/ -t aws://

control 'aws_s3_bucket_policy-exists' do
  impact 1.0
  title 'Manages a aws_s3_bucket_policy resource'
  desc 'Verify that the aws_s3_bucket_policy resource exists and has expected properties'

  describe aws_s3_bucket_policy(name: attribute('id')) do
    it { should exist }
    its('bucket') { should_not be_nil }
    its('policy') { should_not be_nil }
  end
end
