# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_vpc_route_server_vpc_association/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSVpcRouteServerVpcAssociation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_vpc_route_server_vpc_association,
      attributes_class: AWS::Types::VpcRouteServerVpcAssociationAttributes,
      outputs: { id: :id },
      map: [:route_server_id, :vpc_id]
  end
  module AWS
    include AWSVpcRouteServerVpcAssociation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
