# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class Ec2TransitGatewayPeeringAttachmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :peer_region, T::String
    attribute :peer_transit_gateway_id, T::String
    attribute :transit_gateway_id, T::String
    attribute? :options, T::Hash.optional
    attribute? :peer_account_id, T::String.optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
