# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_ssm_activation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSSsmActivation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_ssm_activation,
      attributes_class: AWS::Types::SsmActivationAttributes,
      outputs: { id: :id },
      map: [:iam_role],
      map_present: [:description, :name, :registration_limit, :tags]
  end
  module AWS
    include AWSSsmActivation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
