# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_elastic_beanstalk_application_version/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSElasticBeanstalkApplicationVersion
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_elastic_beanstalk_application_version,
      attributes_class: AWS::Types::ElasticBeanstalkApplicationVersionAttributes,
      outputs: { id: :id },
      map: [:application, :bucket, :key, :name],
      map_present: [:description, :tags, :tags_all],
      map_bool: [:force_delete, :process]
  end
  module AWS
    include AWSElasticBeanstalkApplicationVersion
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
