# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class Route53profilesResourceAssociationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :profile_id, T::String
    attribute :resource_arn, T::String
    attribute? :resource_properties, T::String.optional
  end
end
