# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class FsxS3AccessPointAttachmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute? :openzfs_configuration, T::Array.of(T::Hash).optional
    attribute? :region, T::String.optional
    attribute? :s3_access_point, T::Array.of(T::Hash).optional
  end
end
