# Code generated by pangea-forge.
# InSpec profile for verifying aws_load_balancer_listener_policy infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_load_balancer_listener_policy/ -t aws://

control 'aws_load_balancer_listener_policy-exists' do
  impact 1.0
  title 'Manages a aws_load_balancer_listener_policy resource'
  desc 'Verify that the aws_load_balancer_listener_policy resource exists and has expected properties'

  describe aws_load_balancer_listener_policy(name: attribute('id')) do
    it { should exist }
    its('load_balancer_name') { should_not be_nil }
    its('load_balancer_port') { should_not be_nil }
  end
end
