# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class S3BucketLifecycleConfigurationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :bucket, T::String
    attribute? :expected_bucket_owner, T::String.optional
    attribute? :region, T::String.optional
    attribute? :rule, T::Array.of(T::Hash).optional
    attribute? :transition_default_minimum_object_size, T::String.optional
  end
end
