# Code generated by pangea-forge.
# InSpec profile for verifying aws_qldb_stream infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_qldb_stream/ -t aws://

control 'aws_qldb_stream-exists' do
  impact 1.0
  title 'Manages a aws_qldb_stream resource'
  desc 'Verify that the aws_qldb_stream resource exists and has expected properties'

  describe aws_qldb_stream(name: attribute('id')) do
    it { should exist }
    its('inclusive_start_time') { should_not be_nil }
    its('kinesis_configuration') { should_not be_nil }
    its('ledger_name') { should_not be_nil }
    its('role_arn') { should_not be_nil }
    its('stream_name') { should_not be_nil }
  end
end
