# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class Sesv2AccountVdmAttributesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :vdm_enabled, T::String
    attribute? :dashboard_attributes, T::Hash.optional
    attribute? :guardian_attributes, T::Hash.optional
  end
end
