# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_wafregional_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSWafregionalRule
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_wafregional_rule,
      attributes_class: AWS::Types::WafregionalRuleAttributes,
      outputs: { id: :id },
      map: [:metric_name, :name],
      map_present: [:predicate, :tags, :tags_all]
  end
  module AWS
    include AWSWafregionalRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
