# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RolesanywhereTrustAnchorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :name, T::String
    attribute :source, T::Array.of(T::Hash)
    attribute? :notification_settings, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
  end
end
