# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class VpcEndpointServiceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :acceptance_required, T::Bool
    attribute? :gateway_load_balancer_arns, T::Array.of(T::String).optional
    attribute? :network_load_balancer_arns, T::Array.of(T::String).optional
    attribute? :tags, T::Hash.optional
  end
end
