# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class NetworkAclRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :network_acl_id, T::String
    attribute :protocol, T::String
    attribute :rule_action, T::String
    attribute :rule_number, T::Coercible::Float
    attribute? :cidr_block, T::String.optional
    attribute? :egress, T::Bool.optional
    attribute? :from_port, T::Coercible::Float.optional
    attribute? :icmp_code, T::Coercible::Float.optional
    attribute? :icmp_type, T::Coercible::Float.optional
    attribute? :ipv6_cidr_block, T::String.optional
    attribute? :to_port, T::Coercible::Float.optional
  end
end
