# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_ssoadmin_application_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSSsoadminApplicationAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_ssoadmin_application_assignment,
      attributes_class: AWS::Types::SsoadminApplicationAssignmentAttributes,
      outputs: { id: :id },
      map: [:application_arn, :principal_id, :principal_type],
      map_present: [:region]
  end
  module AWS
    include AWSSsoadminApplicationAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
