# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class PrometheusScraperAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :scrape_configuration, T::String
    attribute? :alias, T::String.optional
    attribute? :destination, T::Array.of(T::Hash).optional
    attribute? :region, T::String.optional
    attribute? :role_configuration, T::Array.of(T::Hash).optional
    attribute? :source, T::Array.of(T::Hash).optional
    attribute? :tags, T::Hash.optional
  end
end
