# Code generated by pangea-forge.
# InSpec profile for verifying aws_elasticsearch_domain infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_elasticsearch_domain/ -t aws://

control 'aws_elasticsearch_domain-exists' do
  impact 1.0
  title 'Manages a aws_elasticsearch_domain resource'
  desc 'Verify that the aws_elasticsearch_domain resource exists and has expected properties'

  describe aws_elasticsearch_domain(name: attribute('id')) do
    it { should exist }
    its('domain_name') { should_not be_nil }
  end
end
