# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class RedshiftClusterSnapshotAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :cluster_identifier, T::String
    attribute :snapshot_identifier, T::String
    attribute? :manual_snapshot_retention_period, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
