# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_lb_trust_store/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSLbTrustStore
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_lb_trust_store,
      attributes_class: AWS::Types::LbTrustStoreAttributes,
      outputs: { id: :id },
      map: [:ca_certificates_bundle_s3_bucket, :ca_certificates_bundle_s3_key],
      map_present: [:ca_certificates_bundle_s3_object_version, :tags]
  end
  module AWS
    include AWSLbTrustStore
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
