# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class WorkspaceswebBrowserSettingsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :browser_policy, T::String
    attribute? :additional_encryption_context, T::Hash.optional
    attribute? :customer_managed_key, T::String.optional
    attribute? :tags, T::Hash.optional
  end
end
