# Code generated by pangea-forge.
# InSpec profile for verifying aws_iam_outbound_web_identity_federation infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_iam_outbound_web_identity_federation/ -t aws://

control 'aws_iam_outbound_web_identity_federation-exists' do
  impact 1.0
  title 'Manages a aws_iam_outbound_web_identity_federation resource'
  desc 'Verify that the aws_iam_outbound_web_identity_federation resource exists and has expected properties'

  describe aws_iam_outbound_web_identity_federation(name: attribute('id')) do
    it { should exist }
  end
end
