# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class AppstreamFleetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :compute_capacity, T::Hash
    attribute :instance_type, T::String
    attribute :name, T::String
    attribute? :domain_join_info, T::Hash.optional
    attribute? :idle_disconnect_timeout_in_seconds, T::Coercible::Float.optional
    attribute? :max_sessions_per_instance, T::Coercible::Float.optional
    attribute? :tags, T::Hash.optional
    attribute? :vpc_config, T::Hash.optional
  end
end
