# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class Route53recoverycontrolconfigControlPanelAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :cluster_arn, T::String
    attribute :name, T::String
    attribute? :tags, T::Hash.optional
    attribute? :tags_all, T::Hash.optional
  end
end
