# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class ArcregionswitchPlanAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :execution_role, T::String
    attribute :name, T::String
    attribute :recovery_approach, T::String
    attribute :regions, T::Array.of(T::String)
    attribute? :associated_alarms, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :primary_region, T::String.optional
    attribute? :recovery_time_objective_minutes, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :region, T::String.optional
    attribute? :tags, T::Hash.optional
    attribute? :triggers, T::Array.of(T::Hash).optional
    attribute? :workflow, T::Array.of(T::Hash).optional
  end
end
