# Code generated by pangea-forge.
# InSpec profile for verifying aws_service_discovery_http_namespace infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_service_discovery_http_namespace/ -t aws://

control 'aws_service_discovery_http_namespace-exists' do
  impact 1.0
  title 'Manages a aws_service_discovery_http_namespace resource'
  desc 'Verify that the aws_service_discovery_http_namespace resource exists and has expected properties'

  describe aws_service_discovery_http_namespace(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
