# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_xray_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSXrayGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_xray_group,
      attributes_class: AWS::Types::XrayGroupAttributes,
      outputs: { id: :id },
      map: [:filter_expression, :group_name],
      map_present: [:insights_configuration, :tags, :tags_all]
  end
  module AWS
    include AWSXrayGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
