# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_ec2_network_insights_analysis/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSEc2NetworkInsightsAnalysis
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_ec2_network_insights_analysis,
      attributes_class: AWS::Types::Ec2NetworkInsightsAnalysisAttributes,
      outputs: { id: :id },
      map: [:network_insights_path_id],
      map_present: [:filter_in_arns, :region, :tags, :tags_all],
      map_bool: [:wait_for_completion]
  end
  module AWS
    include AWSEc2NetworkInsightsAnalysis
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
