# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class CloudwatchLogAccountPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::AWS::Types

    attribute :policy_document, (T::String | T::Hash)
    attribute :policy_name, T::String
    attribute :policy_type, T::String
    attribute? :scope, T::String.optional
    attribute? :selection_criteria, T::String.optional
  end
end
