# Code generated by pangea-forge.
# InSpec profile for verifying aws_neptune_cluster_endpoint infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_neptune_cluster_endpoint/ -t aws://

control 'aws_neptune_cluster_endpoint-exists' do
  impact 1.0
  title 'Manages a aws_neptune_cluster_endpoint resource'
  desc 'Verify that the aws_neptune_cluster_endpoint resource exists and has expected properties'

  describe aws_neptune_cluster_endpoint(name: attribute('id')) do
    it { should exist }
    its('cluster_endpoint_identifier') { should_not be_nil }
    its('cluster_identifier') { should_not be_nil }
    its('endpoint_type') { should_not be_nil }
  end
end
