# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class EmrInstanceFleetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :cluster_id, T::String
    attribute? :instance_type_configs, T::Array.of(T::Hash).optional
    attribute? :launch_specifications, T::Hash.optional
    attribute? :name, T::String.optional
    attribute? :region, T::String.optional
    attribute? :target_on_demand_capacity, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :target_spot_capacity, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
