# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class PaymentcryptographyKeyAliasAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :alias_name, T::String
    attribute? :key_arn, T::String.optional
    attribute? :region, T::String.optional
  end
end
