# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_cloudwatch_log_delivery_destination_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSCloudwatchLogDeliveryDestinationPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_cloudwatch_log_delivery_destination_policy,
      attributes_class: AWS::Types::CloudwatchLogDeliveryDestinationPolicyAttributes,
      outputs: { id: :id },
      map: [:delivery_destination_name, :delivery_destination_policy],
      map_present: [:region]
  end
  module AWS
    include AWSCloudwatchLogDeliveryDestinationPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
