# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_vpc_ipam_pool_cidr_allocation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSVpcIpamPoolCidrAllocation
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_vpc_ipam_pool_cidr_allocation,
      attributes_class: AWS::Types::VpcIpamPoolCidrAllocationAttributes,
      outputs: { id: :id },
      map: [:ipam_pool_id],
      map_present: [:cidr, :description, :disallowed_cidrs, :netmask_length]
  end
  module AWS
    include AWSVpcIpamPoolCidrAllocation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
