# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_servicecatalog_service_action/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSServicecatalogServiceAction
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_servicecatalog_service_action,
      attributes_class: AWS::Types::ServicecatalogServiceActionAttributes,
      outputs: { id: :id },
      map: [:definition, :name],
      map_present: [:accept_language, :description, :region]
  end
  module AWS
    include AWSServicecatalogServiceAction
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
