# Code generated by pangea-forge.
# InSpec profile for verifying aws_cloudwatch_log_delivery infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_cloudwatch_log_delivery/ -t aws://

control 'aws_cloudwatch_log_delivery-exists' do
  impact 1.0
  title 'Manages a aws_cloudwatch_log_delivery resource'
  desc 'Verify that the aws_cloudwatch_log_delivery resource exists and has expected properties'

  describe aws_cloudwatch_log_delivery(name: attribute('id')) do
    it { should exist }
    its('delivery_destination_arn') { should_not be_nil }
    its('delivery_source_name') { should_not be_nil }
  end
end
