# Code generated by pangea-forge.
# InSpec profile for verifying aws_redshift_idc_application infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set AWS_TOKEN and AWS_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/aws_redshift_idc_application/ -t aws://

control 'aws_redshift_idc_application-exists' do
  impact 1.0
  title 'Manages a aws_redshift_idc_application resource'
  desc 'Verify that the aws_redshift_idc_application resource exists and has expected properties'

  describe aws_redshift_idc_application(name: attribute('id')) do
    it { should exist }
    its('iam_role_arn') { should_not be_nil }
    its('idc_display_name') { should_not be_nil }
    its('idc_instance_arn') { should_not be_nil }
    its('redshift_idc_application_name') { should_not be_nil }
  end
end
