# frozen_string_literal: true

# Copyright 2025 The Pangea Authors. Licensed under Apache 2.0.

# Core AWS resources - networking, compute, and basic infrastructure
require 'pangea/resources/base'
require 'pangea/resources/aws_vpc/resource'
require 'pangea/resources/aws_subnet/resource'
require 'pangea/resources/aws_security_group/resource'
require 'pangea/resources/aws_instance/resource'
require 'pangea/resources/aws_internet_gateway/resource'
require 'pangea/resources/aws_route_table/resource'
require 'pangea/resources/aws_nat_gateway/resource'
require 'pangea/resources/aws_route_table_association/resource'
require 'pangea/resources/aws_vpc_endpoint/resource'
require 'pangea/resources/aws_vpc_endpoint_service/resource'
require 'pangea/resources/aws_vpc_peering_connection/resource'
require 'pangea/resources/aws_vpc_peering_connection_accepter/resource'
require 'pangea/resources/aws_vpn_connection/resource'
require 'pangea/resources/aws_vpn_gateway/resource'
require 'pangea/resources/aws_customer_gateway/resource'
require 'pangea/resources/aws_eip/resource'
require 'pangea/resources/aws_eip_association/resource'
require 'pangea/resources/aws_route/resource'
require 'pangea/resources/aws_network_interface/resource'
require 'pangea/resources/aws_network_acl/resource'
require 'pangea/resources/aws_network_acl_rule/resource'
require 'pangea/resources/aws_key_pair/resource'
require 'pangea/resources/aws_ami/resource'
require 'pangea/resources/aws_ec2_transit_gateway/resource'
require 'pangea/resources/aws_ec2_transit_gateway_vpc_attachment/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table_association/resource'
require 'pangea/resources/aws_ec2_transit_gateway_route_table_propagation/resource'
