# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/aws_route53recoverycontrolconfig_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module AWSRoute53recoverycontrolconfigCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :aws_route53recoverycontrolconfig_cluster,
      attributes_class: AWS::Types::Route53recoverycontrolconfigClusterAttributes,
      outputs: { id: :id },
      map: [:name]
  end
  module AWS
    include AWSRoute53recoverycontrolconfigCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::AWS)
