# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_vpn_concentrator resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSVpnConcentrator do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { transit_gateway_id: 'test-value', type: 'test-value' } }

  describe ':aws_vpn_concentrator' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'test')
        validate_required_attributes(config, [:transit_gateway_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_vpn_concentrator('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_vpn_concentrator)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_vpn_concentrator('test', required_attrs)

        expect(ref.id).to eq("${aws_vpn_concentrator.test.id}")
        expect(ref.region).to eq("${aws_vpn_concentrator.test.region}")
        expect(ref.tags_all).to eq("${aws_vpn_concentrator.test.tags_all}")
        expect(ref.transit_gateway_attachment_id).to eq("${aws_vpn_concentrator.test.transit_gateway_attachment_id}")
        expect(ref.vpn_concentrator_id).to eq("${aws_vpn_concentrator.test.vpn_concentrator_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'test')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('transit_gateway_attachment_id')
        expect(config).not_to have_key('vpn_concentrator_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ region: 'test-value', tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'full')
        expect(config).to have_key('region')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpn_concentrator', 'typed')
        expect(config['transit_gateway_id']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpn_concentrator('first', required_attrs)
        synth.aws_vpn_concentrator('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_vpn_concentrator')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_vpn_concentrator,
    method: :aws_vpn_concentrator,
    required_attrs: { transit_gateway_id: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :region, :tags_all, :transit_gateway_attachment_id, :vpn_concentrator_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
