# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_cloudfront_connection_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSCloudfrontConnectionGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':aws_cloudfront_connection_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_cloudfront_connection_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_cloudfront_connection_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_cloudfront_connection_group('test', required_attrs)

        expect(ref.id).to eq("${aws_cloudfront_connection_group.test.id}")
        expect(ref.arn).to eq("${aws_cloudfront_connection_group.test.arn}")
        expect(ref.enabled).to eq("${aws_cloudfront_connection_group.test.enabled}")
        expect(ref.etag).to eq("${aws_cloudfront_connection_group.test.etag}")
        expect(ref.ipv6_enabled).to eq("${aws_cloudfront_connection_group.test.ipv6_enabled}")
        expect(ref.is_default).to eq("${aws_cloudfront_connection_group.test.is_default}")
        expect(ref.last_modified_time).to eq("${aws_cloudfront_connection_group.test.last_modified_time}")
        expect(ref.routing_endpoint).to eq("${aws_cloudfront_connection_group.test.routing_endpoint}")
        expect(ref.status).to eq("${aws_cloudfront_connection_group.test.status}")
        expect(ref.tags_all).to eq("${aws_cloudfront_connection_group.test.tags_all}")
        expect(ref.wait_for_deployment).to eq("${aws_cloudfront_connection_group.test.wait_for_deployment}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('etag')
        expect(config).not_to have_key('ipv6_enabled')
        expect(config).not_to have_key('is_default')
        expect(config).not_to have_key('last_modified_time')
        expect(config).not_to have_key('routing_endpoint')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('wait_for_deployment')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ anycast_ip_list_id: 'test-value', enabled: true, ipv6_enabled: true, tags: { 'key1' => 'val1' }, wait_for_deployment: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'full')
        expect(config).to have_key('anycast_ip_list_id')
        expect(config).to have_key('enabled')
        expect(config).to have_key('ipv6_enabled')
        expect(config).to have_key('tags')
        expect(config).to have_key('wait_for_deployment')
      end
    end

    context 'optional attributes' do
      it 'includes anycast_ip_list_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('opt', required_attrs.merge(anycast_ip_list_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'opt')
        expect(config).to have_key('anycast_ip_list_id')
      end

      it 'omits anycast_ip_list_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'minimal')
        expect(config).not_to have_key('anycast_ip_list_id')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes ipv6_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('opt', required_attrs.merge(ipv6_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'opt')
        expect(config).to have_key('ipv6_enabled')
      end

      it 'omits ipv6_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'minimal')
        expect(config).not_to have_key('ipv6_enabled')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes wait_for_deployment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('opt', required_attrs.merge(wait_for_deployment: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'opt')
        expect(config).to have_key('wait_for_deployment')
      end

      it 'omits wait_for_deployment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'minimal')
        expect(config).not_to have_key('wait_for_deployment')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.aws_cloudfront_connection_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_cloudfront_connection_group', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ipv6_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ipv6_enabled: val)
          synth.aws_cloudfront_connection_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_cloudfront_connection_group', "bool_#{val}")
          expect(config['ipv6_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait_for_deployment=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_deployment: val)
          synth.aws_cloudfront_connection_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_cloudfront_connection_group', "bool_#{val}")
          expect(config['wait_for_deployment']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudfront_connection_group', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudfront_connection_group('first', required_attrs)
        synth.aws_cloudfront_connection_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_cloudfront_connection_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_cloudfront_connection_group,
    method: :aws_cloudfront_connection_group,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :arn, :enabled, :etag, :ipv6_enabled, :is_default, :last_modified_time, :routing_endpoint, :status, :tags_all, :wait_for_deployment],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled, :ipv6_enabled, :wait_for_deployment]
end
