# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_cloudwatch_log_resource_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSCloudwatchLogResourcePolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { policy_document: 'test-value' } }

  describe ':aws_cloudwatch_log_resource_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'test')
        validate_required_attributes(config, [:policy_document])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_cloudwatch_log_resource_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_cloudwatch_log_resource_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_cloudwatch_log_resource_policy('test', required_attrs)

        expect(ref.id).to eq("${aws_cloudwatch_log_resource_policy.test.id}")
        expect(ref.policy_scope).to eq("${aws_cloudwatch_log_resource_policy.test.policy_scope}")
        expect(ref.region).to eq("${aws_cloudwatch_log_resource_policy.test.region}")
        expect(ref.revision_id).to eq("${aws_cloudwatch_log_resource_policy.test.revision_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'test')
        expect(config).not_to have_key('policy_scope')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('revision_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ policy_name: 'test-value', region: 'test-value', resource_arn: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'full')
        expect(config).to have_key('policy_name')
        expect(config).to have_key('region')
        expect(config).to have_key('resource_arn')
      end
    end

    context 'optional attributes' do
      it 'includes policy_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('opt', required_attrs.merge(policy_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'opt')
        expect(config).to have_key('policy_name')
      end

      it 'omits policy_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'minimal')
        expect(config).not_to have_key('policy_name')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes resource_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('opt', required_attrs.merge(resource_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'opt')
        expect(config).to have_key('resource_arn')
      end

      it 'omits resource_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'minimal')
        expect(config).not_to have_key('resource_arn')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_cloudwatch_log_resource_policy', 'typed')
        expect(config['policy_document']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_cloudwatch_log_resource_policy('first', required_attrs)
        synth.aws_cloudwatch_log_resource_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_cloudwatch_log_resource_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_cloudwatch_log_resource_policy,
    method: :aws_cloudwatch_log_resource_policy,
    required_attrs: { policy_document: 'test-value' },
    expected_outputs: [:id, :policy_scope, :region, :revision_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
