# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_lightsail_domain_entry resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSLightsailDomainEntry do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_name: 'test-value', name: 'test-value', target: 'test-value', type: 'test-value' } }

  describe ':aws_lightsail_domain_entry' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'test')
        validate_required_attributes(config, [:domain_name, :name, :target, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lightsail_domain_entry('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_lightsail_domain_entry)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lightsail_domain_entry('test', required_attrs)

        expect(ref.id).to eq("${aws_lightsail_domain_entry.test.id}")
        expect(ref.region).to eq("${aws_lightsail_domain_entry.test.region}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'test')
        expect(config).not_to have_key('region')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ is_alias: true, region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'full')
        expect(config).to have_key('is_alias')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes is_alias when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('opt', required_attrs.merge(is_alias: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'opt')
        expect(config).to have_key('is_alias')
      end

      it 'omits is_alias when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'minimal')
        expect(config).not_to have_key('is_alias')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_alias=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_alias: val)
          synth.aws_lightsail_domain_entry("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_lightsail_domain_entry', "bool_#{val}")
          expect(config['is_alias']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_domain_entry', 'typed')
        expect(config['domain_name']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['target']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_domain_entry('first', required_attrs)
        synth.aws_lightsail_domain_entry('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_lightsail_domain_entry')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_lightsail_domain_entry,
    method: :aws_lightsail_domain_entry,
    required_attrs: { domain_name: 'test-value', name: 'test-value', target: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :region],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_alias]
end
