# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_timestreamquery_scheduled_query resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSTimestreamqueryScheduledQuery do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { execution_role_arn: 'test-value', name: 'test-value', query_string: 'test-value' } }

  describe ':aws_timestreamquery_scheduled_query' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'test')
        validate_required_attributes(config, [:execution_role_arn, :name, :query_string])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_timestreamquery_scheduled_query('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_timestreamquery_scheduled_query)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_timestreamquery_scheduled_query('test', required_attrs)

        expect(ref.id).to eq("${aws_timestreamquery_scheduled_query.test.id}")
        expect(ref.arn).to eq("${aws_timestreamquery_scheduled_query.test.arn}")
        expect(ref.creation_time).to eq("${aws_timestreamquery_scheduled_query.test.creation_time}")
        expect(ref.next_invocation_time).to eq("${aws_timestreamquery_scheduled_query.test.next_invocation_time}")
        expect(ref.previous_invocation_time).to eq("${aws_timestreamquery_scheduled_query.test.previous_invocation_time}")
        expect(ref.state).to eq("${aws_timestreamquery_scheduled_query.test.state}")
        expect(ref.tags_all).to eq("${aws_timestreamquery_scheduled_query.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('creation_time')
        expect(config).not_to have_key('next_invocation_time')
        expect(config).not_to have_key('previous_invocation_time')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ error_report_configuration: [{ 'key1' => 'val1' }], kms_key_id: 'test-value', last_run_summary: [{ 'key1' => 'val1' }], notification_configuration: [{ 'key1' => 'val1' }], recently_failed_runs: [{ 'key1' => 'val1' }], schedule_configuration: [{ 'key1' => 'val1' }], tags: { 'key1' => 'val1' }, target_configuration: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'full')
        expect(config).to have_key('error_report_configuration')
        expect(config).to have_key('kms_key_id')
        expect(config).to have_key('last_run_summary')
        expect(config).to have_key('notification_configuration')
        expect(config).to have_key('recently_failed_runs')
        expect(config).to have_key('schedule_configuration')
        expect(config).to have_key('tags')
        expect(config).to have_key('target_configuration')
      end
    end

    context 'optional attributes' do
      it 'includes error_report_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(error_report_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('error_report_configuration')
      end

      it 'omits error_report_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('error_report_configuration')
      end
      it 'includes kms_key_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(kms_key_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('kms_key_id')
      end

      it 'omits kms_key_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('kms_key_id')
      end
      it 'includes last_run_summary when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(last_run_summary: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('last_run_summary')
      end

      it 'omits last_run_summary when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('last_run_summary')
      end
      it 'includes notification_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(notification_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('notification_configuration')
      end

      it 'omits notification_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('notification_configuration')
      end
      it 'includes recently_failed_runs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(recently_failed_runs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('recently_failed_runs')
      end

      it 'omits recently_failed_runs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('recently_failed_runs')
      end
      it 'includes schedule_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(schedule_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('schedule_configuration')
      end

      it 'omits schedule_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('schedule_configuration')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes target_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('opt', required_attrs.merge(target_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'opt')
        expect(config).to have_key('target_configuration')
      end

      it 'omits target_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'minimal')
        expect(config).not_to have_key('target_configuration')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_timestreamquery_scheduled_query', 'typed')
        expect(config['execution_role_arn']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['query_string']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_timestreamquery_scheduled_query('first', required_attrs)
        synth.aws_timestreamquery_scheduled_query('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_timestreamquery_scheduled_query')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_timestreamquery_scheduled_query,
    method: :aws_timestreamquery_scheduled_query,
    required_attrs: { execution_role_arn: 'test-value', name: 'test-value', query_string: 'test-value' },
    expected_outputs: [:id, :arn, :creation_time, :next_invocation_time, :previous_invocation_time, :state, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
