# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_neptune_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSNeptuneCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':aws_neptune_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_neptune_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_neptune_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_neptune_cluster('test', required_attrs)

        expect(ref.id).to eq("${aws_neptune_cluster.test.id}")
        expect(ref.allow_major_version_upgrade).to eq("${aws_neptune_cluster.test.allow_major_version_upgrade}")
        expect(ref.apply_immediately).to eq("${aws_neptune_cluster.test.apply_immediately}")
        expect(ref.arn).to eq("${aws_neptune_cluster.test.arn}")
        expect(ref.availability_zones).to eq("${aws_neptune_cluster.test.availability_zones}")
        expect(ref.cluster_identifier).to eq("${aws_neptune_cluster.test.cluster_identifier}")
        expect(ref.cluster_identifier_prefix).to eq("${aws_neptune_cluster.test.cluster_identifier_prefix}")
        expect(ref.cluster_members).to eq("${aws_neptune_cluster.test.cluster_members}")
        expect(ref.cluster_resource_id).to eq("${aws_neptune_cluster.test.cluster_resource_id}")
        expect(ref.endpoint).to eq("${aws_neptune_cluster.test.endpoint}")
        expect(ref.engine_version).to eq("${aws_neptune_cluster.test.engine_version}")
        expect(ref.hosted_zone_id).to eq("${aws_neptune_cluster.test.hosted_zone_id}")
        expect(ref.kms_key_arn).to eq("${aws_neptune_cluster.test.kms_key_arn}")
        expect(ref.neptune_cluster_parameter_group_name).to eq("${aws_neptune_cluster.test.neptune_cluster_parameter_group_name}")
        expect(ref.neptune_subnet_group_name).to eq("${aws_neptune_cluster.test.neptune_subnet_group_name}")
        expect(ref.preferred_backup_window).to eq("${aws_neptune_cluster.test.preferred_backup_window}")
        expect(ref.preferred_maintenance_window).to eq("${aws_neptune_cluster.test.preferred_maintenance_window}")
        expect(ref.reader_endpoint).to eq("${aws_neptune_cluster.test.reader_endpoint}")
        expect(ref.region).to eq("${aws_neptune_cluster.test.region}")
        expect(ref.storage_type).to eq("${aws_neptune_cluster.test.storage_type}")
        expect(ref.tags_all).to eq("${aws_neptune_cluster.test.tags_all}")
        expect(ref.vpc_security_group_ids).to eq("${aws_neptune_cluster.test.vpc_security_group_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_neptune_cluster', 'test')
        expect(config).not_to have_key('allow_major_version_upgrade')
        expect(config).not_to have_key('apply_immediately')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('availability_zones')
        expect(config).not_to have_key('cluster_identifier')
        expect(config).not_to have_key('cluster_identifier_prefix')
        expect(config).not_to have_key('cluster_members')
        expect(config).not_to have_key('cluster_resource_id')
        expect(config).not_to have_key('endpoint')
        expect(config).not_to have_key('engine_version')
        expect(config).not_to have_key('hosted_zone_id')
        expect(config).not_to have_key('kms_key_arn')
        expect(config).not_to have_key('neptune_cluster_parameter_group_name')
        expect(config).not_to have_key('neptune_subnet_group_name')
        expect(config).not_to have_key('preferred_backup_window')
        expect(config).not_to have_key('preferred_maintenance_window')
        expect(config).not_to have_key('reader_endpoint')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('storage_type')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('vpc_security_group_ids')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_major_version_upgrade: true, apply_immediately: true, availability_zones: ['test-value'], backup_retention_period: 3.14, cluster_identifier: 'test-value', cluster_identifier_prefix: 'test-value', copy_tags_to_snapshot: true, deletion_protection: true, enable_cloudwatch_logs_exports: ['test-value'], engine: 'test-value', engine_version: 'test-value', final_snapshot_identifier: 'test-value', global_cluster_identifier: 'test-value', iam_database_authentication_enabled: true, iam_roles: ['test-value'], kms_key_arn: 'test-value', neptune_cluster_parameter_group_name: 'test-value', neptune_instance_parameter_group_name: 'test-value', neptune_subnet_group_name: 'test-value', port: 3.14, preferred_backup_window: 'test-value', preferred_maintenance_window: 'test-value', region: 'test-value', replication_source_identifier: 'test-value', serverless_v2_scaling_configuration: { 'key1' => 'val1' }, skip_final_snapshot: true, snapshot_identifier: 'test-value', storage_encrypted: true, storage_type: 'test-value', tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' }, vpc_security_group_ids: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_neptune_cluster', 'full')
        expect(config).to have_key('allow_major_version_upgrade')
        expect(config).to have_key('apply_immediately')
        expect(config).to have_key('availability_zones')
        expect(config).to have_key('backup_retention_period')
        expect(config).to have_key('cluster_identifier')
        expect(config).to have_key('cluster_identifier_prefix')
        expect(config).to have_key('copy_tags_to_snapshot')
        expect(config).to have_key('deletion_protection')
        expect(config).to have_key('enable_cloudwatch_logs_exports')
        expect(config).to have_key('engine')
        expect(config).to have_key('engine_version')
        expect(config).to have_key('final_snapshot_identifier')
        expect(config).to have_key('global_cluster_identifier')
        expect(config).to have_key('iam_database_authentication_enabled')
        expect(config).to have_key('iam_roles')
        expect(config).to have_key('kms_key_arn')
        expect(config).to have_key('neptune_cluster_parameter_group_name')
        expect(config).to have_key('neptune_instance_parameter_group_name')
        expect(config).to have_key('neptune_subnet_group_name')
        expect(config).to have_key('port')
        expect(config).to have_key('preferred_backup_window')
        expect(config).to have_key('preferred_maintenance_window')
        expect(config).to have_key('region')
        expect(config).to have_key('replication_source_identifier')
        expect(config).to have_key('serverless_v2_scaling_configuration')
        expect(config).to have_key('skip_final_snapshot')
        expect(config).to have_key('snapshot_identifier')
        expect(config).to have_key('storage_encrypted')
        expect(config).to have_key('storage_type')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
        expect(config).to have_key('vpc_security_group_ids')
      end
    end

    context 'optional attributes' do
      it 'includes allow_major_version_upgrade when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(allow_major_version_upgrade: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('allow_major_version_upgrade')
      end

      it 'omits allow_major_version_upgrade when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('allow_major_version_upgrade')
      end
      it 'includes apply_immediately when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(apply_immediately: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('apply_immediately')
      end

      it 'omits apply_immediately when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('apply_immediately')
      end
      it 'includes availability_zones when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(availability_zones: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('availability_zones')
      end

      it 'omits availability_zones when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('availability_zones')
      end
      it 'includes backup_retention_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(backup_retention_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('backup_retention_period')
      end

      it 'omits backup_retention_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('backup_retention_period')
      end
      it 'includes cluster_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(cluster_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('cluster_identifier')
      end

      it 'omits cluster_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('cluster_identifier')
      end
      it 'includes cluster_identifier_prefix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(cluster_identifier_prefix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('cluster_identifier_prefix')
      end

      it 'omits cluster_identifier_prefix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('cluster_identifier_prefix')
      end
      it 'includes copy_tags_to_snapshot when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(copy_tags_to_snapshot: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('copy_tags_to_snapshot')
      end

      it 'omits copy_tags_to_snapshot when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('copy_tags_to_snapshot')
      end
      it 'includes deletion_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(deletion_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('deletion_protection')
      end

      it 'omits deletion_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('deletion_protection')
      end
      it 'includes enable_cloudwatch_logs_exports when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(enable_cloudwatch_logs_exports: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('enable_cloudwatch_logs_exports')
      end

      it 'omits enable_cloudwatch_logs_exports when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('enable_cloudwatch_logs_exports')
      end
      it 'includes engine when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(engine: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('engine')
      end

      it 'omits engine when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('engine')
      end
      it 'includes engine_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(engine_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('engine_version')
      end

      it 'omits engine_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('engine_version')
      end
      it 'includes final_snapshot_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(final_snapshot_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('final_snapshot_identifier')
      end

      it 'omits final_snapshot_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('final_snapshot_identifier')
      end
      it 'includes global_cluster_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(global_cluster_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('global_cluster_identifier')
      end

      it 'omits global_cluster_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('global_cluster_identifier')
      end
      it 'includes iam_database_authentication_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(iam_database_authentication_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('iam_database_authentication_enabled')
      end

      it 'omits iam_database_authentication_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('iam_database_authentication_enabled')
      end
      it 'includes iam_roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(iam_roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('iam_roles')
      end

      it 'omits iam_roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('iam_roles')
      end
      it 'includes kms_key_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(kms_key_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('kms_key_arn')
      end

      it 'omits kms_key_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('kms_key_arn')
      end
      it 'includes neptune_cluster_parameter_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(neptune_cluster_parameter_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('neptune_cluster_parameter_group_name')
      end

      it 'omits neptune_cluster_parameter_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('neptune_cluster_parameter_group_name')
      end
      it 'includes neptune_instance_parameter_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(neptune_instance_parameter_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('neptune_instance_parameter_group_name')
      end

      it 'omits neptune_instance_parameter_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('neptune_instance_parameter_group_name')
      end
      it 'includes neptune_subnet_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(neptune_subnet_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('neptune_subnet_group_name')
      end

      it 'omits neptune_subnet_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('neptune_subnet_group_name')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes preferred_backup_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(preferred_backup_window: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('preferred_backup_window')
      end

      it 'omits preferred_backup_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('preferred_backup_window')
      end
      it 'includes preferred_maintenance_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(preferred_maintenance_window: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('preferred_maintenance_window')
      end

      it 'omits preferred_maintenance_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('preferred_maintenance_window')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes replication_source_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(replication_source_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('replication_source_identifier')
      end

      it 'omits replication_source_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('replication_source_identifier')
      end
      it 'includes serverless_v2_scaling_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(serverless_v2_scaling_configuration: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('serverless_v2_scaling_configuration')
      end

      it 'omits serverless_v2_scaling_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('serverless_v2_scaling_configuration')
      end
      it 'includes skip_final_snapshot when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(skip_final_snapshot: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('skip_final_snapshot')
      end

      it 'omits skip_final_snapshot when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('skip_final_snapshot')
      end
      it 'includes snapshot_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(snapshot_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('snapshot_identifier')
      end

      it 'omits snapshot_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('snapshot_identifier')
      end
      it 'includes storage_encrypted when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(storage_encrypted: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('storage_encrypted')
      end

      it 'omits storage_encrypted when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('storage_encrypted')
      end
      it 'includes storage_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(storage_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('storage_type')
      end

      it 'omits storage_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('storage_type')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
      it 'includes vpc_security_group_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('opt', required_attrs.merge(vpc_security_group_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'opt')
        expect(config).to have_key('vpc_security_group_ids')
      end

      it 'omits vpc_security_group_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_neptune_cluster', 'minimal')
        expect(config).not_to have_key('vpc_security_group_ids')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_major_version_upgrade=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_major_version_upgrade: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['allow_major_version_upgrade']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts apply_immediately=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(apply_immediately: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['apply_immediately']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts copy_tags_to_snapshot=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(copy_tags_to_snapshot: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['copy_tags_to_snapshot']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts deletion_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deletion_protection: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['deletion_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts iam_database_authentication_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(iam_database_authentication_enabled: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['iam_database_authentication_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_final_snapshot=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_final_snapshot: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['skip_final_snapshot']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts storage_encrypted=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(storage_encrypted: val)
          synth.aws_neptune_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_neptune_cluster', "bool_#{val}")
          expect(config['storage_encrypted']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_neptune_cluster', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_neptune_cluster('first', required_attrs)
        synth.aws_neptune_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_neptune_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_neptune_cluster,
    method: :aws_neptune_cluster,
    required_attrs: {},
    expected_outputs: [:id, :allow_major_version_upgrade, :apply_immediately, :arn, :availability_zones, :cluster_identifier, :cluster_identifier_prefix, :cluster_members, :cluster_resource_id, :endpoint, :engine_version, :hosted_zone_id, :kms_key_arn, :neptune_cluster_parameter_group_name, :neptune_subnet_group_name, :preferred_backup_window, :preferred_maintenance_window, :reader_endpoint, :region, :storage_type, :tags_all, :vpc_security_group_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_major_version_upgrade, :apply_immediately, :copy_tags_to_snapshot, :deletion_protection, :iam_database_authentication_enabled, :skip_final_snapshot, :storage_encrypted]
end
