# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_ec2_local_gateway_route_table_vpc_association resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSEc2LocalGatewayRouteTableVpcAssociation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { local_gateway_route_table_id: 'test-value', vpc_id: 'test-value' } }

  describe ':aws_ec2_local_gateway_route_table_vpc_association' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'test')
        validate_required_attributes(config, [:local_gateway_route_table_id, :vpc_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_ec2_local_gateway_route_table_vpc_association('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_ec2_local_gateway_route_table_vpc_association)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_ec2_local_gateway_route_table_vpc_association('test', required_attrs)

        expect(ref.id).to eq("${aws_ec2_local_gateway_route_table_vpc_association.test.id}")
        expect(ref.local_gateway_id).to eq("${aws_ec2_local_gateway_route_table_vpc_association.test.local_gateway_id}")
        expect(ref.region).to eq("${aws_ec2_local_gateway_route_table_vpc_association.test.region}")
        expect(ref.tags_all).to eq("${aws_ec2_local_gateway_route_table_vpc_association.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'test')
        expect(config).not_to have_key('local_gateway_id')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ region: 'test-value', tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'full')
        expect(config).to have_key('region')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
      end
    end

    context 'optional attributes' do
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_ec2_local_gateway_route_table_vpc_association', 'typed')
        expect(config['local_gateway_route_table_id']).to be_a(String)
        expect(config['vpc_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_ec2_local_gateway_route_table_vpc_association('first', required_attrs)
        synth.aws_ec2_local_gateway_route_table_vpc_association('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_ec2_local_gateway_route_table_vpc_association')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_ec2_local_gateway_route_table_vpc_association,
    method: :aws_ec2_local_gateway_route_table_vpc_association,
    required_attrs: { local_gateway_route_table_id: 'test-value', vpc_id: 'test-value' },
    expected_outputs: [:id, :local_gateway_id, :region, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
