# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_chatbot_slack_channel_configuration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSChatbotSlackChannelConfiguration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { configuration_name: 'test-value', iam_role_arn: 'test-value', slack_channel_id: 'test-value', slack_team_id: 'test-value' } }

  describe ':aws_chatbot_slack_channel_configuration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'test')
        validate_required_attributes(config, [:configuration_name, :iam_role_arn, :slack_channel_id, :slack_team_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_chatbot_slack_channel_configuration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_chatbot_slack_channel_configuration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_chatbot_slack_channel_configuration('test', required_attrs)

        expect(ref.id).to eq("${aws_chatbot_slack_channel_configuration.test.id}")
        expect(ref.chat_configuration_arn).to eq("${aws_chatbot_slack_channel_configuration.test.chat_configuration_arn}")
        expect(ref.guardrail_policy_arns).to eq("${aws_chatbot_slack_channel_configuration.test.guardrail_policy_arns}")
        expect(ref.logging_level).to eq("${aws_chatbot_slack_channel_configuration.test.logging_level}")
        expect(ref.slack_channel_name).to eq("${aws_chatbot_slack_channel_configuration.test.slack_channel_name}")
        expect(ref.slack_team_name).to eq("${aws_chatbot_slack_channel_configuration.test.slack_team_name}")
        expect(ref.sns_topic_arns).to eq("${aws_chatbot_slack_channel_configuration.test.sns_topic_arns}")
        expect(ref.tags_all).to eq("${aws_chatbot_slack_channel_configuration.test.tags_all}")
        expect(ref.user_authorization_required).to eq("${aws_chatbot_slack_channel_configuration.test.user_authorization_required}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'test')
        expect(config).not_to have_key('chat_configuration_arn')
        expect(config).not_to have_key('guardrail_policy_arns')
        expect(config).not_to have_key('logging_level')
        expect(config).not_to have_key('slack_channel_name')
        expect(config).not_to have_key('slack_team_name')
        expect(config).not_to have_key('sns_topic_arns')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('user_authorization_required')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'full')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_chatbot_slack_channel_configuration', 'typed')
        expect(config['configuration_name']).to be_a(String)
        expect(config['iam_role_arn']).to be_a(String)
        expect(config['slack_channel_id']).to be_a(String)
        expect(config['slack_team_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_chatbot_slack_channel_configuration('first', required_attrs)
        synth.aws_chatbot_slack_channel_configuration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_chatbot_slack_channel_configuration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_chatbot_slack_channel_configuration,
    method: :aws_chatbot_slack_channel_configuration,
    required_attrs: { configuration_name: 'test-value', iam_role_arn: 'test-value', slack_channel_id: 'test-value', slack_team_id: 'test-value' },
    expected_outputs: [:id, :chat_configuration_arn, :guardrail_policy_arns, :logging_level, :slack_channel_name, :slack_team_name, :sns_topic_arns, :tags_all, :user_authorization_required],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
