# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_config_configuration_recorder resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSConfigConfigurationRecorder do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_arn: 'test-value' } }

  describe ':aws_config_configuration_recorder' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'test')
        validate_required_attributes(config, [:role_arn])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_config_configuration_recorder('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_config_configuration_recorder)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_config_configuration_recorder('test', required_attrs)

        expect(ref.id).to eq("${aws_config_configuration_recorder.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value', recording_group: [{ 'key1' => 'val1' }], recording_mode: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'full')
        expect(config).to have_key('name')
        expect(config).to have_key('recording_group')
        expect(config).to have_key('recording_mode')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes recording_group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('opt', required_attrs.merge(recording_group: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'opt')
        expect(config).to have_key('recording_group')
      end

      it 'omits recording_group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'minimal')
        expect(config).not_to have_key('recording_group')
      end
      it 'includes recording_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('opt', required_attrs.merge(recording_mode: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'opt')
        expect(config).to have_key('recording_mode')
      end

      it 'omits recording_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'minimal')
        expect(config).not_to have_key('recording_mode')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_config_configuration_recorder', 'typed')
        expect(config['role_arn']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_configuration_recorder('first', required_attrs)
        synth.aws_config_configuration_recorder('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_config_configuration_recorder')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_config_configuration_recorder,
    method: :aws_config_configuration_recorder,
    required_attrs: { role_arn: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
