# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_fsx_ontap_file_system resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSFsxOntapFileSystem do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { deployment_type: 'test-value', preferred_subnet_id: 'test-value', storage_capacity: 3.14, subnet_ids: ['test-value'] } }

  describe ':aws_fsx_ontap_file_system' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'test')
        validate_required_attributes(config, [:deployment_type, :preferred_subnet_id, :storage_capacity, :subnet_ids])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_fsx_ontap_file_system('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_fsx_ontap_file_system)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_fsx_ontap_file_system('test', required_attrs)

        expect(ref.id).to eq("${aws_fsx_ontap_file_system.test.id}")
        expect(ref.arn).to eq("${aws_fsx_ontap_file_system.test.arn}")
        expect(ref.daily_automatic_backup_start_time).to eq("${aws_fsx_ontap_file_system.test.daily_automatic_backup_start_time}")
        expect(ref.dns_name).to eq("${aws_fsx_ontap_file_system.test.dns_name}")
        expect(ref.endpoint_ip_address_range).to eq("${aws_fsx_ontap_file_system.test.endpoint_ip_address_range}")
        expect(ref.endpoints).to eq("${aws_fsx_ontap_file_system.test.endpoints}")
        expect(ref.ha_pairs).to eq("${aws_fsx_ontap_file_system.test.ha_pairs}")
        expect(ref.kms_key_id).to eq("${aws_fsx_ontap_file_system.test.kms_key_id}")
        expect(ref.network_interface_ids).to eq("${aws_fsx_ontap_file_system.test.network_interface_ids}")
        expect(ref.owner_id).to eq("${aws_fsx_ontap_file_system.test.owner_id}")
        expect(ref.region).to eq("${aws_fsx_ontap_file_system.test.region}")
        expect(ref.route_table_ids).to eq("${aws_fsx_ontap_file_system.test.route_table_ids}")
        expect(ref.tags_all).to eq("${aws_fsx_ontap_file_system.test.tags_all}")
        expect(ref.throughput_capacity).to eq("${aws_fsx_ontap_file_system.test.throughput_capacity}")
        expect(ref.throughput_capacity_per_ha_pair).to eq("${aws_fsx_ontap_file_system.test.throughput_capacity_per_ha_pair}")
        expect(ref.vpc_id).to eq("${aws_fsx_ontap_file_system.test.vpc_id}")
        expect(ref.weekly_maintenance_start_time).to eq("${aws_fsx_ontap_file_system.test.weekly_maintenance_start_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('daily_automatic_backup_start_time')
        expect(config).not_to have_key('dns_name')
        expect(config).not_to have_key('endpoint_ip_address_range')
        expect(config).not_to have_key('endpoints')
        expect(config).not_to have_key('ha_pairs')
        expect(config).not_to have_key('kms_key_id')
        expect(config).not_to have_key('network_interface_ids')
        expect(config).not_to have_key('owner_id')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('route_table_ids')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('throughput_capacity')
        expect(config).not_to have_key('throughput_capacity_per_ha_pair')
        expect(config).not_to have_key('vpc_id')
        expect(config).not_to have_key('weekly_maintenance_start_time')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ automatic_backup_retention_days: 3.14, daily_automatic_backup_start_time: 'test-value', disk_iops_configuration: { 'key1' => 'val1' }, endpoint_ip_address_range: 'test-value', fsx_admin_password: 'test-value', ha_pairs: 3.14, kms_key_id: 'test-value', region: 'test-value', route_table_ids: ['test-value'], security_group_ids: ['test-value'], storage_type: 'test-value', tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' }, throughput_capacity: 3.14, throughput_capacity_per_ha_pair: 3.14, weekly_maintenance_start_time: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'full')
        expect(config).to have_key('automatic_backup_retention_days')
        expect(config).to have_key('daily_automatic_backup_start_time')
        expect(config).to have_key('disk_iops_configuration')
        expect(config).to have_key('endpoint_ip_address_range')
        expect(config).to have_key('fsx_admin_password')
        expect(config).to have_key('ha_pairs')
        expect(config).to have_key('kms_key_id')
        expect(config).to have_key('region')
        expect(config).to have_key('route_table_ids')
        expect(config).to have_key('security_group_ids')
        expect(config).to have_key('storage_type')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
        expect(config).to have_key('throughput_capacity')
        expect(config).to have_key('throughput_capacity_per_ha_pair')
        expect(config).to have_key('weekly_maintenance_start_time')
      end
    end

    context 'optional attributes' do
      it 'includes automatic_backup_retention_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(automatic_backup_retention_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('automatic_backup_retention_days')
      end

      it 'omits automatic_backup_retention_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('automatic_backup_retention_days')
      end
      it 'includes daily_automatic_backup_start_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(daily_automatic_backup_start_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('daily_automatic_backup_start_time')
      end

      it 'omits daily_automatic_backup_start_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('daily_automatic_backup_start_time')
      end
      it 'includes disk_iops_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(disk_iops_configuration: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('disk_iops_configuration')
      end

      it 'omits disk_iops_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('disk_iops_configuration')
      end
      it 'includes endpoint_ip_address_range when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(endpoint_ip_address_range: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('endpoint_ip_address_range')
      end

      it 'omits endpoint_ip_address_range when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('endpoint_ip_address_range')
      end
      it 'includes fsx_admin_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(fsx_admin_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('fsx_admin_password')
      end

      it 'omits fsx_admin_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('fsx_admin_password')
      end
      it 'includes ha_pairs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(ha_pairs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('ha_pairs')
      end

      it 'omits ha_pairs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('ha_pairs')
      end
      it 'includes kms_key_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(kms_key_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('kms_key_id')
      end

      it 'omits kms_key_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('kms_key_id')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes route_table_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(route_table_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('route_table_ids')
      end

      it 'omits route_table_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('route_table_ids')
      end
      it 'includes security_group_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(security_group_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('security_group_ids')
      end

      it 'omits security_group_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('security_group_ids')
      end
      it 'includes storage_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(storage_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('storage_type')
      end

      it 'omits storage_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('storage_type')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
      it 'includes throughput_capacity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(throughput_capacity: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('throughput_capacity')
      end

      it 'omits throughput_capacity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('throughput_capacity')
      end
      it 'includes throughput_capacity_per_ha_pair when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(throughput_capacity_per_ha_pair: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('throughput_capacity_per_ha_pair')
      end

      it 'omits throughput_capacity_per_ha_pair when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('throughput_capacity_per_ha_pair')
      end
      it 'includes weekly_maintenance_start_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('opt', required_attrs.merge(weekly_maintenance_start_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'opt')
        expect(config).to have_key('weekly_maintenance_start_time')
      end

      it 'omits weekly_maintenance_start_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'minimal')
        expect(config).not_to have_key('weekly_maintenance_start_time')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:fsx_admin_password]
        expect(sensitive_fields).to include(:fsx_admin_password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_fsx_ontap_file_system', 'typed')
        expect(config['deployment_type']).to be_a(String)
        expect(config['preferred_subnet_id']).to be_a(String)
        expect(config['storage_capacity']).to be_a(Float)
        expect(config['subnet_ids']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_fsx_ontap_file_system('first', required_attrs)
        synth.aws_fsx_ontap_file_system('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_fsx_ontap_file_system')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_fsx_ontap_file_system,
    method: :aws_fsx_ontap_file_system,
    required_attrs: { deployment_type: 'test-value', preferred_subnet_id: 'test-value', storage_capacity: 3.14, subnet_ids: ['test-value'] },
    expected_outputs: [:id, :arn, :daily_automatic_backup_start_time, :dns_name, :endpoint_ip_address_range, :endpoints, :ha_pairs, :kms_key_id, :network_interface_ids, :owner_id, :region, :route_table_ids, :tags_all, :throughput_capacity, :throughput_capacity_per_ha_pair, :vpc_id, :weekly_maintenance_start_time],
    sensitive_fields: [:fsx_admin_password],
    immutable_fields: [],
    boolean_fields: []
end
