# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_lakeformation_resource_lf_tags resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSLakeformationResourceLfTags do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { lf_tag: [{ 'key1' => 'val1' }] } }

  describe ':aws_lakeformation_resource_lf_tags' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'test')
        validate_required_attributes(config, [:lf_tag])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lakeformation_resource_lf_tags('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_lakeformation_resource_lf_tags)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lakeformation_resource_lf_tags('test', required_attrs)

        expect(ref.id).to eq("${aws_lakeformation_resource_lf_tags.test.id}")
        expect(ref.catalog_id).to eq("${aws_lakeformation_resource_lf_tags.test.catalog_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'test')
        expect(config).not_to have_key('catalog_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ database: [{ 'key1' => 'val1' }], table: [{ 'key1' => 'val1' }], table_with_columns: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'full')
        expect(config).to have_key('database')
        expect(config).to have_key('table')
        expect(config).to have_key('table_with_columns')
      end
    end

    context 'optional attributes' do
      it 'includes database when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('opt', required_attrs.merge(database: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'opt')
        expect(config).to have_key('database')
      end

      it 'omits database when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'minimal')
        expect(config).not_to have_key('database')
      end
      it 'includes table when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('opt', required_attrs.merge(table: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'opt')
        expect(config).to have_key('table')
      end

      it 'omits table when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'minimal')
        expect(config).not_to have_key('table')
      end
      it 'includes table_with_columns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('opt', required_attrs.merge(table_with_columns: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'opt')
        expect(config).to have_key('table_with_columns')
      end

      it 'omits table_with_columns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'minimal')
        expect(config).not_to have_key('table_with_columns')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lakeformation_resource_lf_tags', 'typed')
        expect(config['lf_tag']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lakeformation_resource_lf_tags('first', required_attrs)
        synth.aws_lakeformation_resource_lf_tags('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_lakeformation_resource_lf_tags')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_lakeformation_resource_lf_tags,
    method: :aws_lakeformation_resource_lf_tags,
    required_attrs: { lf_tag: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :catalog_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
