# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_rds_custom_db_engine_version resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSRdsCustomDbEngineVersion do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { engine: 'test-value', engine_version: 'test-value' } }

  describe ':aws_rds_custom_db_engine_version' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'test')
        validate_required_attributes(config, [:engine, :engine_version])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_rds_custom_db_engine_version('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_rds_custom_db_engine_version)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_rds_custom_db_engine_version('test', required_attrs)

        expect(ref.id).to eq("${aws_rds_custom_db_engine_version.test.id}")
        expect(ref.arn).to eq("${aws_rds_custom_db_engine_version.test.arn}")
        expect(ref.create_time).to eq("${aws_rds_custom_db_engine_version.test.create_time}")
        expect(ref.db_parameter_group_family).to eq("${aws_rds_custom_db_engine_version.test.db_parameter_group_family}")
        expect(ref.image_id).to eq("${aws_rds_custom_db_engine_version.test.image_id}")
        expect(ref.kms_key_id).to eq("${aws_rds_custom_db_engine_version.test.kms_key_id}")
        expect(ref.major_engine_version).to eq("${aws_rds_custom_db_engine_version.test.major_engine_version}")
        expect(ref.manifest_computed).to eq("${aws_rds_custom_db_engine_version.test.manifest_computed}")
        expect(ref.region).to eq("${aws_rds_custom_db_engine_version.test.region}")
        expect(ref.status).to eq("${aws_rds_custom_db_engine_version.test.status}")
        expect(ref.tags_all).to eq("${aws_rds_custom_db_engine_version.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('db_parameter_group_family')
        expect(config).not_to have_key('image_id')
        expect(config).not_to have_key('kms_key_id')
        expect(config).not_to have_key('major_engine_version')
        expect(config).not_to have_key('manifest_computed')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ database_installation_files_s3_bucket_name: 'test-value', database_installation_files_s3_prefix: 'test-value', description: 'test-value', filename: 'test-value', kms_key_id: 'test-value', manifest: 'test-value', manifest_hash: 'test-value', region: 'test-value', source_image_id: 'test-value', status: 'test-value', tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'full')
        expect(config).to have_key('database_installation_files_s3_bucket_name')
        expect(config).to have_key('database_installation_files_s3_prefix')
        expect(config).to have_key('description')
        expect(config).to have_key('filename')
        expect(config).to have_key('kms_key_id')
        expect(config).to have_key('manifest')
        expect(config).to have_key('manifest_hash')
        expect(config).to have_key('region')
        expect(config).to have_key('source_image_id')
        expect(config).to have_key('status')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
      end
    end

    context 'optional attributes' do
      it 'includes database_installation_files_s3_bucket_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(database_installation_files_s3_bucket_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('database_installation_files_s3_bucket_name')
      end

      it 'omits database_installation_files_s3_bucket_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('database_installation_files_s3_bucket_name')
      end
      it 'includes database_installation_files_s3_prefix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(database_installation_files_s3_prefix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('database_installation_files_s3_prefix')
      end

      it 'omits database_installation_files_s3_prefix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('database_installation_files_s3_prefix')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes filename when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(filename: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('filename')
      end

      it 'omits filename when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('filename')
      end
      it 'includes kms_key_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(kms_key_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('kms_key_id')
      end

      it 'omits kms_key_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('kms_key_id')
      end
      it 'includes manifest when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(manifest: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('manifest')
      end

      it 'omits manifest when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('manifest')
      end
      it 'includes manifest_hash when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(manifest_hash: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('manifest_hash')
      end

      it 'omits manifest_hash when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('manifest_hash')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes source_image_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(source_image_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('source_image_id')
      end

      it 'omits source_image_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('source_image_id')
      end
      it 'includes status when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(status: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('status')
      end

      it 'omits status when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('status')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_rds_custom_db_engine_version', 'typed')
        expect(config['engine']).to be_a(String)
        expect(config['engine_version']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_rds_custom_db_engine_version('first', required_attrs)
        synth.aws_rds_custom_db_engine_version('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_rds_custom_db_engine_version')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_rds_custom_db_engine_version,
    method: :aws_rds_custom_db_engine_version,
    required_attrs: { engine: 'test-value', engine_version: 'test-value' },
    expected_outputs: [:id, :arn, :create_time, :db_parameter_group_family, :image_id, :kms_key_id, :major_engine_version, :manifest_computed, :region, :status, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
