# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_amplify_webhook resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSAmplifyWebhook do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app_id: 'test-value', branch_name: 'test-value' } }

  describe ':aws_amplify_webhook' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_amplify_webhook', 'test')
        validate_required_attributes(config, [:app_id, :branch_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_amplify_webhook('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_amplify_webhook)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_amplify_webhook('test', required_attrs)

        expect(ref.id).to eq("${aws_amplify_webhook.test.id}")
        expect(ref.arn).to eq("${aws_amplify_webhook.test.arn}")
        expect(ref.region).to eq("${aws_amplify_webhook.test.region}")
        expect(ref.url).to eq("${aws_amplify_webhook.test.url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_amplify_webhook', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_amplify_webhook', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_amplify_webhook', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_amplify_webhook', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_amplify_webhook', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_amplify_webhook', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_amplify_webhook', 'typed')
        expect(config['app_id']).to be_a(String)
        expect(config['branch_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_amplify_webhook('first', required_attrs)
        synth.aws_amplify_webhook('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_amplify_webhook')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_amplify_webhook,
    method: :aws_amplify_webhook,
    required_attrs: { app_id: 'test-value', branch_name: 'test-value' },
    expected_outputs: [:id, :arn, :region, :url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
