# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_vpc_ipam_pool_cidr resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSVpcIpamPoolCidr do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { ipam_pool_id: 'test-value' } }

  describe ':aws_vpc_ipam_pool_cidr' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'test')
        validate_required_attributes(config, [:ipam_pool_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_vpc_ipam_pool_cidr('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_vpc_ipam_pool_cidr)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_vpc_ipam_pool_cidr('test', required_attrs)

        expect(ref.id).to eq("${aws_vpc_ipam_pool_cidr.test.id}")
        expect(ref.cidr).to eq("${aws_vpc_ipam_pool_cidr.test.cidr}")
        expect(ref.ipam_pool_cidr_id).to eq("${aws_vpc_ipam_pool_cidr.test.ipam_pool_cidr_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'test')
        expect(config).not_to have_key('cidr')
        expect(config).not_to have_key('ipam_pool_cidr_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cidr_authorization_context: [{ 'key1' => 'val1' }], netmask_length: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'full')
        expect(config).to have_key('cidr_authorization_context')
        expect(config).to have_key('netmask_length')
      end
    end

    context 'optional attributes' do
      it 'includes cidr_authorization_context when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('opt', required_attrs.merge(cidr_authorization_context: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'opt')
        expect(config).to have_key('cidr_authorization_context')
      end

      it 'omits cidr_authorization_context when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'minimal')
        expect(config).not_to have_key('cidr_authorization_context')
      end
      it 'includes netmask_length when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('opt', required_attrs.merge(netmask_length: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'opt')
        expect(config).to have_key('netmask_length')
      end

      it 'omits netmask_length when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'minimal')
        expect(config).not_to have_key('netmask_length')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_vpc_ipam_pool_cidr', 'typed')
        expect(config['ipam_pool_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_vpc_ipam_pool_cidr('first', required_attrs)
        synth.aws_vpc_ipam_pool_cidr('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_vpc_ipam_pool_cidr')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_vpc_ipam_pool_cidr,
    method: :aws_vpc_ipam_pool_cidr,
    required_attrs: { ipam_pool_id: 'test-value' },
    expected_outputs: [:id, :cidr, :ipam_pool_cidr_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
