# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_customerprofiles_domain resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSCustomerprofilesDomain do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { default_expiration_days: 3.14, domain_name: 'test-value' } }

  describe ':aws_customerprofiles_domain' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'test')
        validate_required_attributes(config, [:default_expiration_days, :domain_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_customerprofiles_domain('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_customerprofiles_domain)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_customerprofiles_domain('test', required_attrs)

        expect(ref.id).to eq("${aws_customerprofiles_domain.test.id}")
        expect(ref.arn).to eq("${aws_customerprofiles_domain.test.arn}")
        expect(ref.tags_all).to eq("${aws_customerprofiles_domain.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dead_letter_queue_url: 'test-value', default_encryption_key: 'test-value', matching: [{ 'key1' => 'val1' }], rule_based_matching: [{ 'key1' => 'val1' }], tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'full')
        expect(config).to have_key('dead_letter_queue_url')
        expect(config).to have_key('default_encryption_key')
        expect(config).to have_key('matching')
        expect(config).to have_key('rule_based_matching')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes dead_letter_queue_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('opt', required_attrs.merge(dead_letter_queue_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'opt')
        expect(config).to have_key('dead_letter_queue_url')
      end

      it 'omits dead_letter_queue_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'minimal')
        expect(config).not_to have_key('dead_letter_queue_url')
      end
      it 'includes default_encryption_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('opt', required_attrs.merge(default_encryption_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'opt')
        expect(config).to have_key('default_encryption_key')
      end

      it 'omits default_encryption_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'minimal')
        expect(config).not_to have_key('default_encryption_key')
      end
      it 'includes matching when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('opt', required_attrs.merge(matching: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'opt')
        expect(config).to have_key('matching')
      end

      it 'omits matching when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'minimal')
        expect(config).not_to have_key('matching')
      end
      it 'includes rule_based_matching when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('opt', required_attrs.merge(rule_based_matching: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'opt')
        expect(config).to have_key('rule_based_matching')
      end

      it 'omits rule_based_matching when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'minimal')
        expect(config).not_to have_key('rule_based_matching')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_customerprofiles_domain', 'typed')
        expect(config['default_expiration_days']).to be_a(Float)
        expect(config['domain_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_customerprofiles_domain('first', required_attrs)
        synth.aws_customerprofiles_domain('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_customerprofiles_domain')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_customerprofiles_domain,
    method: :aws_customerprofiles_domain,
    required_attrs: { default_expiration_days: 3.14, domain_name: 'test-value' },
    expected_outputs: [:id, :arn, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
