# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_servicecatalog_portfolio_share resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSServicecatalogPortfolioShare do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { portfolio_id: 'test-value', principal_id: 'test-value', type: 'test-value' } }

  describe ':aws_servicecatalog_portfolio_share' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'test')
        validate_required_attributes(config, [:portfolio_id, :principal_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_servicecatalog_portfolio_share('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_servicecatalog_portfolio_share)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_servicecatalog_portfolio_share('test', required_attrs)

        expect(ref.id).to eq("${aws_servicecatalog_portfolio_share.test.id}")
        expect(ref.accepted).to eq("${aws_servicecatalog_portfolio_share.test.accepted}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'test')
        expect(config).not_to have_key('accepted')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ accept_language: 'test-value', share_principals: true, share_tag_options: true, wait_for_acceptance: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'full')
        expect(config).to have_key('accept_language')
        expect(config).to have_key('share_principals')
        expect(config).to have_key('share_tag_options')
        expect(config).to have_key('wait_for_acceptance')
      end
    end

    context 'optional attributes' do
      it 'includes accept_language when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('opt', required_attrs.merge(accept_language: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'opt')
        expect(config).to have_key('accept_language')
      end

      it 'omits accept_language when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'minimal')
        expect(config).not_to have_key('accept_language')
      end
      it 'includes share_principals when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('opt', required_attrs.merge(share_principals: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'opt')
        expect(config).to have_key('share_principals')
      end

      it 'omits share_principals when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'minimal')
        expect(config).not_to have_key('share_principals')
      end
      it 'includes share_tag_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('opt', required_attrs.merge(share_tag_options: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'opt')
        expect(config).to have_key('share_tag_options')
      end

      it 'omits share_tag_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'minimal')
        expect(config).not_to have_key('share_tag_options')
      end
      it 'includes wait_for_acceptance when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('opt', required_attrs.merge(wait_for_acceptance: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'opt')
        expect(config).to have_key('wait_for_acceptance')
      end

      it 'omits wait_for_acceptance when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'minimal')
        expect(config).not_to have_key('wait_for_acceptance')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts share_principals=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(share_principals: val)
          synth.aws_servicecatalog_portfolio_share("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', "bool_#{val}")
          expect(config['share_principals']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts share_tag_options=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(share_tag_options: val)
          synth.aws_servicecatalog_portfolio_share("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', "bool_#{val}")
          expect(config['share_tag_options']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait_for_acceptance=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_acceptance: val)
          synth.aws_servicecatalog_portfolio_share("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', "bool_#{val}")
          expect(config['wait_for_acceptance']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_servicecatalog_portfolio_share', 'typed')
        expect(config['portfolio_id']).to be_a(String)
        expect(config['principal_id']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_servicecatalog_portfolio_share('first', required_attrs)
        synth.aws_servicecatalog_portfolio_share('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_servicecatalog_portfolio_share')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_servicecatalog_portfolio_share,
    method: :aws_servicecatalog_portfolio_share,
    required_attrs: { portfolio_id: 'test-value', principal_id: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :accepted],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:share_principals, :share_tag_options, :wait_for_acceptance]
end
