# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_codepipeline_custom_action_type resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSCodepipelineCustomActionType do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { category: 'test-value', input_artifact_details: { 'key1' => 'val1' }, output_artifact_details: { 'key1' => 'val1' }, provider_name: 'test-value', version: 'test-value' } }

  describe ':aws_codepipeline_custom_action_type' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'test')
        validate_required_attributes(config, [:category, :input_artifact_details, :output_artifact_details, :provider_name, :version])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_codepipeline_custom_action_type('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_codepipeline_custom_action_type)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_codepipeline_custom_action_type('test', required_attrs)

        expect(ref.id).to eq("${aws_codepipeline_custom_action_type.test.id}")
        expect(ref.arn).to eq("${aws_codepipeline_custom_action_type.test.arn}")
        expect(ref.owner).to eq("${aws_codepipeline_custom_action_type.test.owner}")
        expect(ref.region).to eq("${aws_codepipeline_custom_action_type.test.region}")
        expect(ref.tags_all).to eq("${aws_codepipeline_custom_action_type.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('owner')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ configuration_property: [{ 'key1' => 'val1' }], region: 'test-value', settings: { 'key1' => 'val1' }, tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'full')
        expect(config).to have_key('configuration_property')
        expect(config).to have_key('region')
        expect(config).to have_key('settings')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
      end
    end

    context 'optional attributes' do
      it 'includes configuration_property when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('opt', required_attrs.merge(configuration_property: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'opt')
        expect(config).to have_key('configuration_property')
      end

      it 'omits configuration_property when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'minimal')
        expect(config).not_to have_key('configuration_property')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('opt', required_attrs.merge(settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'opt')
        expect(config).to have_key('settings')
      end

      it 'omits settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'minimal')
        expect(config).not_to have_key('settings')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codepipeline_custom_action_type', 'typed')
        expect(config['category']).to be_a(String)
        expect(config['input_artifact_details']).to be_a(Hash)
        expect(config['output_artifact_details']).to be_a(Hash)
        expect(config['provider_name']).to be_a(String)
        expect(config['version']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codepipeline_custom_action_type('first', required_attrs)
        synth.aws_codepipeline_custom_action_type('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_codepipeline_custom_action_type')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_codepipeline_custom_action_type,
    method: :aws_codepipeline_custom_action_type,
    required_attrs: { category: 'test-value', input_artifact_details: { 'key1' => 'val1' }, output_artifact_details: { 'key1' => 'val1' }, provider_name: 'test-value', version: 'test-value' },
    expected_outputs: [:id, :arn, :owner, :region, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
