# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_route53_resolver_endpoint resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSRoute53ResolverEndpoint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { direction: 'test-value', ip_address: [{ 'key1' => 'val1' }], security_group_ids: ['test-value'] } }

  describe ':aws_route53_resolver_endpoint' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'test')
        validate_required_attributes(config, [:direction, :ip_address, :security_group_ids])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_route53_resolver_endpoint('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_route53_resolver_endpoint)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_route53_resolver_endpoint('test', required_attrs)

        expect(ref.id).to eq("${aws_route53_resolver_endpoint.test.id}")
        expect(ref.arn).to eq("${aws_route53_resolver_endpoint.test.arn}")
        expect(ref.host_vpc_id).to eq("${aws_route53_resolver_endpoint.test.host_vpc_id}")
        expect(ref.protocols).to eq("${aws_route53_resolver_endpoint.test.protocols}")
        expect(ref.resolver_endpoint_type).to eq("${aws_route53_resolver_endpoint.test.resolver_endpoint_type}")
        expect(ref.tags_all).to eq("${aws_route53_resolver_endpoint.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('host_vpc_id')
        expect(config).not_to have_key('protocols')
        expect(config).not_to have_key('resolver_endpoint_type')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value', tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'full')
        expect(config).to have_key('name')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_route53_resolver_endpoint', 'typed')
        expect(config['direction']).to be_a(String)
        expect(config['ip_address']).to be_a(Array)
        expect(config['security_group_ids']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_route53_resolver_endpoint('first', required_attrs)
        synth.aws_route53_resolver_endpoint('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_route53_resolver_endpoint')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_route53_resolver_endpoint,
    method: :aws_route53_resolver_endpoint,
    required_attrs: { direction: 'test-value', ip_address: [{ 'key1' => 'val1' }], security_group_ids: ['test-value'] },
    expected_outputs: [:id, :arn, :host_vpc_id, :protocols, :resolver_endpoint_type, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
