# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_lightsail_bucket resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSLightsailBucket do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { bundle_id: 'test-value', name: 'test-value' } }

  describe ':aws_lightsail_bucket' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'test')
        validate_required_attributes(config, [:bundle_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lightsail_bucket('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_lightsail_bucket)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_lightsail_bucket('test', required_attrs)

        expect(ref.id).to eq("${aws_lightsail_bucket.test.id}")
        expect(ref.arn).to eq("${aws_lightsail_bucket.test.arn}")
        expect(ref.availability_zone).to eq("${aws_lightsail_bucket.test.availability_zone}")
        expect(ref.created_at).to eq("${aws_lightsail_bucket.test.created_at}")
        expect(ref.region).to eq("${aws_lightsail_bucket.test.region}")
        expect(ref.support_code).to eq("${aws_lightsail_bucket.test.support_code}")
        expect(ref.tags_all).to eq("${aws_lightsail_bucket.test.tags_all}")
        expect(ref.url).to eq("${aws_lightsail_bucket.test.url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('availability_zone')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('support_code')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ force_delete: true, region: 'test-value', tags: { 'key1' => 'val1' }, tags_all: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'full')
        expect(config).to have_key('force_delete')
        expect(config).to have_key('region')
        expect(config).to have_key('tags')
        expect(config).to have_key('tags_all')
      end
    end

    context 'optional attributes' do
      it 'includes force_delete when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('opt', required_attrs.merge(force_delete: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'opt')
        expect(config).to have_key('force_delete')
      end

      it 'omits force_delete when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'minimal')
        expect(config).not_to have_key('force_delete')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tags_all when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('opt', required_attrs.merge(tags_all: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'opt')
        expect(config).to have_key('tags_all')
      end

      it 'omits tags_all when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'minimal')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force_delete=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_delete: val)
          synth.aws_lightsail_bucket("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_lightsail_bucket', "bool_#{val}")
          expect(config['force_delete']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_lightsail_bucket', 'typed')
        expect(config['bundle_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_lightsail_bucket('first', required_attrs)
        synth.aws_lightsail_bucket('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_lightsail_bucket')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_lightsail_bucket,
    method: :aws_lightsail_bucket,
    required_attrs: { bundle_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :arn, :availability_zone, :created_at, :region, :support_code, :tags_all, :url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force_delete]
end
