# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_codebuild_fleet resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSCodebuildFleet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { base_capacity: 3.14, compute_type: 'test-value', environment_type: 'test-value', name: 'test-value' } }

  describe ':aws_codebuild_fleet' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'test')
        validate_required_attributes(config, [:base_capacity, :compute_type, :environment_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_codebuild_fleet('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_codebuild_fleet)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_codebuild_fleet('test', required_attrs)

        expect(ref.id).to eq("${aws_codebuild_fleet.test.id}")
        expect(ref.arn).to eq("${aws_codebuild_fleet.test.arn}")
        expect(ref.created).to eq("${aws_codebuild_fleet.test.created}")
        expect(ref.last_modified).to eq("${aws_codebuild_fleet.test.last_modified}")
        expect(ref.overflow_behavior).to eq("${aws_codebuild_fleet.test.overflow_behavior}")
        expect(ref.status).to eq("${aws_codebuild_fleet.test.status}")
        expect(ref.tags_all).to eq("${aws_codebuild_fleet.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('last_modified')
        expect(config).not_to have_key('overflow_behavior')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ compute_configuration: [{ 'key1' => 'val1' }], fleet_service_role: 'test-value', image_id: 'test-value', scaling_configuration: [{ 'key1' => 'val1' }], tags: { 'key1' => 'val1' }, vpc_config: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'full')
        expect(config).to have_key('compute_configuration')
        expect(config).to have_key('fleet_service_role')
        expect(config).to have_key('image_id')
        expect(config).to have_key('scaling_configuration')
        expect(config).to have_key('tags')
        expect(config).to have_key('vpc_config')
      end
    end

    context 'optional attributes' do
      it 'includes compute_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(compute_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('compute_configuration')
      end

      it 'omits compute_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('compute_configuration')
      end
      it 'includes fleet_service_role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(fleet_service_role: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('fleet_service_role')
      end

      it 'omits fleet_service_role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('fleet_service_role')
      end
      it 'includes image_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(image_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('image_id')
      end

      it 'omits image_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('image_id')
      end
      it 'includes scaling_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(scaling_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('scaling_configuration')
      end

      it 'omits scaling_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('scaling_configuration')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes vpc_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('opt', required_attrs.merge(vpc_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'opt')
        expect(config).to have_key('vpc_config')
      end

      it 'omits vpc_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'minimal')
        expect(config).not_to have_key('vpc_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_codebuild_fleet', 'typed')
        expect(config['base_capacity']).to be_a(Float)
        expect(config['compute_type']).to be_a(String)
        expect(config['environment_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_codebuild_fleet('first', required_attrs)
        synth.aws_codebuild_fleet('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_codebuild_fleet')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_codebuild_fleet,
    method: :aws_codebuild_fleet,
    required_attrs: { base_capacity: 3.14, compute_type: 'test-value', environment_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :arn, :created, :last_modified, :overflow_behavior, :status, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
