# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_elasticache_global_replication_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSElasticacheGlobalReplicationGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { global_replication_group_id_suffix: 'test-value', primary_replication_group_id: 'test-value' } }

  describe ':aws_elasticache_global_replication_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'test')
        validate_required_attributes(config, [:global_replication_group_id_suffix, :primary_replication_group_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_elasticache_global_replication_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_elasticache_global_replication_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_elasticache_global_replication_group('test', required_attrs)

        expect(ref.id).to eq("${aws_elasticache_global_replication_group.test.id}")
        expect(ref.arn).to eq("${aws_elasticache_global_replication_group.test.arn}")
        expect(ref.at_rest_encryption_enabled).to eq("${aws_elasticache_global_replication_group.test.at_rest_encryption_enabled}")
        expect(ref.auth_token_enabled).to eq("${aws_elasticache_global_replication_group.test.auth_token_enabled}")
        expect(ref.automatic_failover_enabled).to eq("${aws_elasticache_global_replication_group.test.automatic_failover_enabled}")
        expect(ref.cache_node_type).to eq("${aws_elasticache_global_replication_group.test.cache_node_type}")
        expect(ref.cluster_enabled).to eq("${aws_elasticache_global_replication_group.test.cluster_enabled}")
        expect(ref.engine).to eq("${aws_elasticache_global_replication_group.test.engine}")
        expect(ref.engine_version).to eq("${aws_elasticache_global_replication_group.test.engine_version}")
        expect(ref.engine_version_actual).to eq("${aws_elasticache_global_replication_group.test.engine_version_actual}")
        expect(ref.global_node_groups).to eq("${aws_elasticache_global_replication_group.test.global_node_groups}")
        expect(ref.global_replication_group_id).to eq("${aws_elasticache_global_replication_group.test.global_replication_group_id}")
        expect(ref.num_node_groups).to eq("${aws_elasticache_global_replication_group.test.num_node_groups}")
        expect(ref.region).to eq("${aws_elasticache_global_replication_group.test.region}")
        expect(ref.transit_encryption_enabled).to eq("${aws_elasticache_global_replication_group.test.transit_encryption_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('at_rest_encryption_enabled')
        expect(config).not_to have_key('auth_token_enabled')
        expect(config).not_to have_key('automatic_failover_enabled')
        expect(config).not_to have_key('cache_node_type')
        expect(config).not_to have_key('cluster_enabled')
        expect(config).not_to have_key('engine')
        expect(config).not_to have_key('engine_version')
        expect(config).not_to have_key('engine_version_actual')
        expect(config).not_to have_key('global_node_groups')
        expect(config).not_to have_key('global_replication_group_id')
        expect(config).not_to have_key('num_node_groups')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('transit_encryption_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ automatic_failover_enabled: true, cache_node_type: 'test-value', engine: 'test-value', engine_version: 'test-value', global_replication_group_description: 'test-value', num_node_groups: 3.14, parameter_group_name: 'test-value', region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'full')
        expect(config).to have_key('automatic_failover_enabled')
        expect(config).to have_key('cache_node_type')
        expect(config).to have_key('engine')
        expect(config).to have_key('engine_version')
        expect(config).to have_key('global_replication_group_description')
        expect(config).to have_key('num_node_groups')
        expect(config).to have_key('parameter_group_name')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes automatic_failover_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(automatic_failover_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('automatic_failover_enabled')
      end

      it 'omits automatic_failover_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('automatic_failover_enabled')
      end
      it 'includes cache_node_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(cache_node_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('cache_node_type')
      end

      it 'omits cache_node_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('cache_node_type')
      end
      it 'includes engine when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(engine: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('engine')
      end

      it 'omits engine when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('engine')
      end
      it 'includes engine_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(engine_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('engine_version')
      end

      it 'omits engine_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('engine_version')
      end
      it 'includes global_replication_group_description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(global_replication_group_description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('global_replication_group_description')
      end

      it 'omits global_replication_group_description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('global_replication_group_description')
      end
      it 'includes num_node_groups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(num_node_groups: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('num_node_groups')
      end

      it 'omits num_node_groups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('num_node_groups')
      end
      it 'includes parameter_group_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(parameter_group_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('parameter_group_name')
      end

      it 'omits parameter_group_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('parameter_group_name')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automatic_failover_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automatic_failover_enabled: val)
          synth.aws_elasticache_global_replication_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', "bool_#{val}")
          expect(config['automatic_failover_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_elasticache_global_replication_group', 'typed')
        expect(config['global_replication_group_id_suffix']).to be_a(String)
        expect(config['primary_replication_group_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_elasticache_global_replication_group('first', required_attrs)
        synth.aws_elasticache_global_replication_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_elasticache_global_replication_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_elasticache_global_replication_group,
    method: :aws_elasticache_global_replication_group,
    required_attrs: { global_replication_group_id_suffix: 'test-value', primary_replication_group_id: 'test-value' },
    expected_outputs: [:id, :arn, :at_rest_encryption_enabled, :auth_token_enabled, :automatic_failover_enabled, :cache_node_type, :cluster_enabled, :engine, :engine_version, :engine_version_actual, :global_node_groups, :global_replication_group_id, :num_node_groups, :region, :transit_encryption_enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:automatic_failover_enabled]
end
