# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_appsync_source_api_association resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSAppsyncSourceApiAssociation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':aws_appsync_source_api_association' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_appsync_source_api_association('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_appsync_source_api_association)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_appsync_source_api_association('test', required_attrs)

        expect(ref.id).to eq("${aws_appsync_source_api_association.test.id}")
        expect(ref.arn).to eq("${aws_appsync_source_api_association.test.arn}")
        expect(ref.association_id).to eq("${aws_appsync_source_api_association.test.association_id}")
        expect(ref.merged_api_arn).to eq("${aws_appsync_source_api_association.test.merged_api_arn}")
        expect(ref.merged_api_id).to eq("${aws_appsync_source_api_association.test.merged_api_id}")
        expect(ref.source_api_arn).to eq("${aws_appsync_source_api_association.test.source_api_arn}")
        expect(ref.source_api_association_config).to eq("${aws_appsync_source_api_association.test.source_api_association_config}")
        expect(ref.source_api_id).to eq("${aws_appsync_source_api_association.test.source_api_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('association_id')
        expect(config).not_to have_key('merged_api_arn')
        expect(config).not_to have_key('merged_api_id')
        expect(config).not_to have_key('source_api_arn')
        expect(config).not_to have_key('source_api_association_config')
        expect(config).not_to have_key('source_api_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_appsync_source_api_association', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_appsync_source_api_association('first', required_attrs)
        synth.aws_appsync_source_api_association('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_appsync_source_api_association')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_appsync_source_api_association,
    method: :aws_appsync_source_api_association,
    required_attrs: {},
    expected_outputs: [:id, :arn, :association_id, :merged_api_arn, :merged_api_id, :source_api_arn, :source_api_association_config, :source_api_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
