# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_networkflowmonitor_scope resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSNetworkflowmonitorScope do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':aws_networkflowmonitor_scope' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_networkflowmonitor_scope('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_networkflowmonitor_scope)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_networkflowmonitor_scope('test', required_attrs)

        expect(ref.id).to eq("${aws_networkflowmonitor_scope.test.id}")
        expect(ref.region).to eq("${aws_networkflowmonitor_scope.test.region}")
        expect(ref.scope_arn).to eq("${aws_networkflowmonitor_scope.test.scope_arn}")
        expect(ref.scope_id).to eq("${aws_networkflowmonitor_scope.test.scope_id}")
        expect(ref.tags_all).to eq("${aws_networkflowmonitor_scope.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'test')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('scope_arn')
        expect(config).not_to have_key('scope_id')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ region: 'test-value', tags: { 'key1' => 'val1' }, target: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'full')
        expect(config).to have_key('region')
        expect(config).to have_key('tags')
        expect(config).to have_key('target')
      end
    end

    context 'optional attributes' do
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes target when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('opt', required_attrs.merge(target: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'opt')
        expect(config).to have_key('target')
      end

      it 'omits target when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'minimal')
        expect(config).not_to have_key('target')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkflowmonitor_scope', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkflowmonitor_scope('first', required_attrs)
        synth.aws_networkflowmonitor_scope('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_networkflowmonitor_scope')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_networkflowmonitor_scope,
    method: :aws_networkflowmonitor_scope,
    required_attrs: {},
    expected_outputs: [:id, :region, :scope_arn, :scope_id, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
