# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_sagemaker_human_task_ui resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSSagemakerHumanTaskUi do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { human_task_ui_name: 'test-value', ui_template: [{ 'key1' => 'val1' }] } }

  describe ':aws_sagemaker_human_task_ui' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'test')
        validate_required_attributes(config, [:human_task_ui_name, :ui_template])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_sagemaker_human_task_ui('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_sagemaker_human_task_ui)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_sagemaker_human_task_ui('test', required_attrs)

        expect(ref.id).to eq("${aws_sagemaker_human_task_ui.test.id}")
        expect(ref.arn).to eq("${aws_sagemaker_human_task_ui.test.arn}")
        expect(ref.tags_all).to eq("${aws_sagemaker_human_task_ui.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'full')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_sagemaker_human_task_ui', 'typed')
        expect(config['human_task_ui_name']).to be_a(String)
        expect(config['ui_template']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_sagemaker_human_task_ui('first', required_attrs)
        synth.aws_sagemaker_human_task_ui('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_sagemaker_human_task_ui')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_sagemaker_human_task_ui,
    method: :aws_sagemaker_human_task_ui,
    required_attrs: { human_task_ui_name: 'test-value', ui_template: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :arn, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
