# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_pinpointsmsvoicev2_phone_number resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSPinpointsmsvoicev2PhoneNumber do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { iso_country_code: 'test-value', message_type: 'test-value', number_capabilities: ['test-value'], number_type: 'test-value' } }

  describe ':aws_pinpointsmsvoicev2_phone_number' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'test')
        validate_required_attributes(config, [:iso_country_code, :message_type, :number_capabilities, :number_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_pinpointsmsvoicev2_phone_number('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_pinpointsmsvoicev2_phone_number)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_pinpointsmsvoicev2_phone_number('test', required_attrs)

        expect(ref.id).to eq("${aws_pinpointsmsvoicev2_phone_number.test.id}")
        expect(ref.arn).to eq("${aws_pinpointsmsvoicev2_phone_number.test.arn}")
        expect(ref.deletion_protection_enabled).to eq("${aws_pinpointsmsvoicev2_phone_number.test.deletion_protection_enabled}")
        expect(ref.monthly_leasing_price).to eq("${aws_pinpointsmsvoicev2_phone_number.test.monthly_leasing_price}")
        expect(ref.opt_out_list_name).to eq("${aws_pinpointsmsvoicev2_phone_number.test.opt_out_list_name}")
        expect(ref.phone_number).to eq("${aws_pinpointsmsvoicev2_phone_number.test.phone_number}")
        expect(ref.self_managed_opt_outs_enabled).to eq("${aws_pinpointsmsvoicev2_phone_number.test.self_managed_opt_outs_enabled}")
        expect(ref.tags_all).to eq("${aws_pinpointsmsvoicev2_phone_number.test.tags_all}")
        expect(ref.two_way_channel_enabled).to eq("${aws_pinpointsmsvoicev2_phone_number.test.two_way_channel_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('deletion_protection_enabled')
        expect(config).not_to have_key('monthly_leasing_price')
        expect(config).not_to have_key('opt_out_list_name')
        expect(config).not_to have_key('phone_number')
        expect(config).not_to have_key('self_managed_opt_outs_enabled')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('two_way_channel_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ registration_id: 'test-value', tags: { 'key1' => 'val1' }, two_way_channel_arn: 'test-value', two_way_channel_role: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'full')
        expect(config).to have_key('registration_id')
        expect(config).to have_key('tags')
        expect(config).to have_key('two_way_channel_arn')
        expect(config).to have_key('two_way_channel_role')
      end
    end

    context 'optional attributes' do
      it 'includes registration_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('opt', required_attrs.merge(registration_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'opt')
        expect(config).to have_key('registration_id')
      end

      it 'omits registration_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'minimal')
        expect(config).not_to have_key('registration_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes two_way_channel_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('opt', required_attrs.merge(two_way_channel_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'opt')
        expect(config).to have_key('two_way_channel_arn')
      end

      it 'omits two_way_channel_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'minimal')
        expect(config).not_to have_key('two_way_channel_arn')
      end
      it 'includes two_way_channel_role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('opt', required_attrs.merge(two_way_channel_role: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'opt')
        expect(config).to have_key('two_way_channel_role')
      end

      it 'omits two_way_channel_role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'minimal')
        expect(config).not_to have_key('two_way_channel_role')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_pinpointsmsvoicev2_phone_number', 'typed')
        expect(config['iso_country_code']).to be_a(String)
        expect(config['message_type']).to be_a(String)
        expect(config['number_capabilities']).to be_a(Array)
        expect(config['number_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_pinpointsmsvoicev2_phone_number('first', required_attrs)
        synth.aws_pinpointsmsvoicev2_phone_number('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_pinpointsmsvoicev2_phone_number')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_pinpointsmsvoicev2_phone_number,
    method: :aws_pinpointsmsvoicev2_phone_number,
    required_attrs: { iso_country_code: 'test-value', message_type: 'test-value', number_capabilities: ['test-value'], number_type: 'test-value' },
    expected_outputs: [:id, :arn, :deletion_protection_enabled, :monthly_leasing_price, :opt_out_list_name, :phone_number, :self_managed_opt_outs_enabled, :tags_all, :two_way_channel_enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
