# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_config_organization_managed_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSConfigOrganizationManagedRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', rule_identifier: 'test-value' } }

  describe ':aws_config_organization_managed_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'test')
        validate_required_attributes(config, [:name, :rule_identifier])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_config_organization_managed_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_config_organization_managed_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_config_organization_managed_rule('test', required_attrs)

        expect(ref.id).to eq("${aws_config_organization_managed_rule.test.id}")
        expect(ref.arn).to eq("${aws_config_organization_managed_rule.test.arn}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'test')
        expect(config).not_to have_key('arn')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', excluded_accounts: ['test-value'], input_parameters: 'test-value', maximum_execution_frequency: 'test-value', resource_id_scope: 'test-value', resource_types_scope: ['test-value'], tag_key_scope: 'test-value', tag_value_scope: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('excluded_accounts')
        expect(config).to have_key('input_parameters')
        expect(config).to have_key('maximum_execution_frequency')
        expect(config).to have_key('resource_id_scope')
        expect(config).to have_key('resource_types_scope')
        expect(config).to have_key('tag_key_scope')
        expect(config).to have_key('tag_value_scope')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes excluded_accounts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(excluded_accounts: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('excluded_accounts')
      end

      it 'omits excluded_accounts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('excluded_accounts')
      end
      it 'includes input_parameters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(input_parameters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('input_parameters')
      end

      it 'omits input_parameters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('input_parameters')
      end
      it 'includes maximum_execution_frequency when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(maximum_execution_frequency: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('maximum_execution_frequency')
      end

      it 'omits maximum_execution_frequency when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('maximum_execution_frequency')
      end
      it 'includes resource_id_scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(resource_id_scope: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('resource_id_scope')
      end

      it 'omits resource_id_scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('resource_id_scope')
      end
      it 'includes resource_types_scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(resource_types_scope: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('resource_types_scope')
      end

      it 'omits resource_types_scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('resource_types_scope')
      end
      it 'includes tag_key_scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(tag_key_scope: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('tag_key_scope')
      end

      it 'omits tag_key_scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('tag_key_scope')
      end
      it 'includes tag_value_scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('opt', required_attrs.merge(tag_value_scope: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'opt')
        expect(config).to have_key('tag_value_scope')
      end

      it 'omits tag_value_scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'minimal')
        expect(config).not_to have_key('tag_value_scope')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_config_organization_managed_rule', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['rule_identifier']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_config_organization_managed_rule('first', required_attrs)
        synth.aws_config_organization_managed_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_config_organization_managed_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_config_organization_managed_rule,
    method: :aws_config_organization_managed_rule,
    required_attrs: { name: 'test-value', rule_identifier: 'test-value' },
    expected_outputs: [:id, :arn],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
