# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_datazone_project resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSDatazoneProject do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_identifier: 'test-value', name: 'test-value' } }

  describe ':aws_datazone_project' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_datazone_project', 'test')
        validate_required_attributes(config, [:domain_identifier, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_datazone_project('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_datazone_project)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_datazone_project('test', required_attrs)

        expect(ref.id).to eq("${aws_datazone_project.test.id}")
        expect(ref.created_at).to eq("${aws_datazone_project.test.created_at}")
        expect(ref.created_by).to eq("${aws_datazone_project.test.created_by}")
        expect(ref.failure_reasons).to eq("${aws_datazone_project.test.failure_reasons}")
        expect(ref.last_updated_at).to eq("${aws_datazone_project.test.last_updated_at}")
        expect(ref.project_status).to eq("${aws_datazone_project.test.project_status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_datazone_project', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('failure_reasons')
        expect(config).not_to have_key('last_updated_at')
        expect(config).not_to have_key('project_status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', glossary_terms: ['test-value'], skip_deletion_check: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_datazone_project', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('glossary_terms')
        expect(config).to have_key('skip_deletion_check')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes glossary_terms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('opt', required_attrs.merge(glossary_terms: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'opt')
        expect(config).to have_key('glossary_terms')
      end

      it 'omits glossary_terms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'minimal')
        expect(config).not_to have_key('glossary_terms')
      end
      it 'includes skip_deletion_check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('opt', required_attrs.merge(skip_deletion_check: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'opt')
        expect(config).to have_key('skip_deletion_check')
      end

      it 'omits skip_deletion_check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_datazone_project', 'minimal')
        expect(config).not_to have_key('skip_deletion_check')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts skip_deletion_check=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_deletion_check: val)
          synth.aws_datazone_project("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_datazone_project', "bool_#{val}")
          expect(config['skip_deletion_check']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_datazone_project', 'typed')
        expect(config['domain_identifier']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_datazone_project('first', required_attrs)
        synth.aws_datazone_project('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_datazone_project')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_datazone_project,
    method: :aws_datazone_project,
    required_attrs: { domain_identifier: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created_at, :created_by, :failure_reasons, :last_updated_at, :project_status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:skip_deletion_check]
end
