# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_apigatewayv2_routing_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSApigatewayv2RoutingRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_name: 'test-value', priority: 3.14 } }

  describe ':aws_apigatewayv2_routing_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'test')
        validate_required_attributes(config, [:domain_name, :priority])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_apigatewayv2_routing_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_apigatewayv2_routing_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_apigatewayv2_routing_rule('test', required_attrs)

        expect(ref.id).to eq("${aws_apigatewayv2_routing_rule.test.id}")
        expect(ref.region).to eq("${aws_apigatewayv2_routing_rule.test.region}")
        expect(ref.routing_rule_arn).to eq("${aws_apigatewayv2_routing_rule.test.routing_rule_arn}")
        expect(ref.routing_rule_id).to eq("${aws_apigatewayv2_routing_rule.test.routing_rule_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'test')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('routing_rule_arn')
        expect(config).not_to have_key('routing_rule_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ action: [{ 'key1' => 'val1' }], condition: [{ 'key1' => 'val1' }], region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'full')
        expect(config).to have_key('action')
        expect(config).to have_key('condition')
        expect(config).to have_key('region')
      end
    end

    context 'optional attributes' do
      it 'includes action when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('opt', required_attrs.merge(action: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'opt')
        expect(config).to have_key('action')
      end

      it 'omits action when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'minimal')
        expect(config).not_to have_key('action')
      end
      it 'includes condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('opt', required_attrs.merge(condition: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'opt')
        expect(config).to have_key('condition')
      end

      it 'omits condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'minimal')
        expect(config).not_to have_key('condition')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'minimal')
        expect(config).not_to have_key('region')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_apigatewayv2_routing_rule', 'typed')
        expect(config['domain_name']).to be_a(String)
        expect(config['priority']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_apigatewayv2_routing_rule('first', required_attrs)
        synth.aws_apigatewayv2_routing_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_apigatewayv2_routing_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_apigatewayv2_routing_rule,
    method: :aws_apigatewayv2_routing_rule,
    required_attrs: { domain_name: 'test-value', priority: 3.14 },
    expected_outputs: [:id, :region, :routing_rule_arn, :routing_rule_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
