# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_nat_gateway resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSNatGateway do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { subnet_id: 'test-value' } }

  describe ':aws_nat_gateway' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'test')
        validate_required_attributes(config, [:subnet_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_nat_gateway('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_nat_gateway)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_nat_gateway('test', required_attrs)

        expect(ref.id).to eq("${aws_nat_gateway.test.id}")
        expect(ref.association_id).to eq("${aws_nat_gateway.test.association_id}")
        expect(ref.network_interface_id).to eq("${aws_nat_gateway.test.network_interface_id}")
        expect(ref.private_ip).to eq("${aws_nat_gateway.test.private_ip}")
        expect(ref.public_ip).to eq("${aws_nat_gateway.test.public_ip}")
        expect(ref.secondary_private_ip_address_count).to eq("${aws_nat_gateway.test.secondary_private_ip_address_count}")
        expect(ref.secondary_private_ip_addresses).to eq("${aws_nat_gateway.test.secondary_private_ip_addresses}")
        expect(ref.tags_all).to eq("${aws_nat_gateway.test.tags_all}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_nat_gateway', 'test')
        expect(config).not_to have_key('association_id')
        expect(config).not_to have_key('network_interface_id')
        expect(config).not_to have_key('private_ip')
        expect(config).not_to have_key('public_ip')
        expect(config).not_to have_key('secondary_private_ip_address_count')
        expect(config).not_to have_key('secondary_private_ip_addresses')
        expect(config).not_to have_key('tags_all')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allocation_id: 'test-value', connectivity_type: 'test-value', secondary_allocation_ids: ['test-value'], tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_nat_gateway', 'full')
        expect(config).to have_key('allocation_id')
        expect(config).to have_key('connectivity_type')
        expect(config).to have_key('secondary_allocation_ids')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes allocation_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('opt', required_attrs.merge(allocation_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'opt')
        expect(config).to have_key('allocation_id')
      end

      it 'omits allocation_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'minimal')
        expect(config).not_to have_key('allocation_id')
      end
      it 'includes connectivity_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('opt', required_attrs.merge(connectivity_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'opt')
        expect(config).to have_key('connectivity_type')
      end

      it 'omits connectivity_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'minimal')
        expect(config).not_to have_key('connectivity_type')
      end
      it 'includes secondary_allocation_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('opt', required_attrs.merge(secondary_allocation_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'opt')
        expect(config).to have_key('secondary_allocation_ids')
      end

      it 'omits secondary_allocation_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'minimal')
        expect(config).not_to have_key('secondary_allocation_ids')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_nat_gateway', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_nat_gateway', 'typed')
        expect(config['subnet_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_nat_gateway('first', required_attrs)
        synth.aws_nat_gateway('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_nat_gateway')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_nat_gateway,
    method: :aws_nat_gateway,
    required_attrs: { subnet_id: 'test-value' },
    expected_outputs: [:id, :association_id, :network_interface_id, :private_ip, :public_ip, :secondary_private_ip_address_count, :secondary_private_ip_addresses, :tags_all],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
