# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_secretsmanager_secret_rotation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSSecretsmanagerSecretRotation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { rotation_rules: [{ 'key1' => 'val1' }], secret_id: 'test-value' } }

  describe ':aws_secretsmanager_secret_rotation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'test')
        validate_required_attributes(config, [:rotation_rules, :secret_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_secretsmanager_secret_rotation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_secretsmanager_secret_rotation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_secretsmanager_secret_rotation('test', required_attrs)

        expect(ref.id).to eq("${aws_secretsmanager_secret_rotation.test.id}")
        expect(ref.rotation_enabled).to eq("${aws_secretsmanager_secret_rotation.test.rotation_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'test')
        expect(config).not_to have_key('rotation_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ rotate_immediately: true, rotation_lambda_arn: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'full')
        expect(config).to have_key('rotate_immediately')
        expect(config).to have_key('rotation_lambda_arn')
      end
    end

    context 'optional attributes' do
      it 'includes rotate_immediately when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('opt', required_attrs.merge(rotate_immediately: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'opt')
        expect(config).to have_key('rotate_immediately')
      end

      it 'omits rotate_immediately when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'minimal')
        expect(config).not_to have_key('rotate_immediately')
      end
      it 'includes rotation_lambda_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('opt', required_attrs.merge(rotation_lambda_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'opt')
        expect(config).to have_key('rotation_lambda_arn')
      end

      it 'omits rotation_lambda_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'minimal')
        expect(config).not_to have_key('rotation_lambda_arn')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts rotate_immediately=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(rotate_immediately: val)
          synth.aws_secretsmanager_secret_rotation("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', "bool_#{val}")
          expect(config['rotate_immediately']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_secretsmanager_secret_rotation', 'typed')
        expect(config['rotation_rules']).to be_a(Array)
        expect(config['secret_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_secretsmanager_secret_rotation('first', required_attrs)
        synth.aws_secretsmanager_secret_rotation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_secretsmanager_secret_rotation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_secretsmanager_secret_rotation,
    method: :aws_secretsmanager_secret_rotation,
    required_attrs: { rotation_rules: [{ 'key1' => 'val1' }], secret_id: 'test-value' },
    expected_outputs: [:id, :rotation_enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:rotate_immediately]
end
