# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_networkfirewall_firewall resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSNetworkfirewallFirewall do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { firewall_policy_arn: 'test-value', name: 'test-value', subnet_mapping: [{ 'key1' => 'val1' }], vpc_id: 'test-value' } }

  describe ':aws_networkfirewall_firewall' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'test')
        validate_required_attributes(config, [:firewall_policy_arn, :name, :subnet_mapping, :vpc_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_networkfirewall_firewall('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_networkfirewall_firewall)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_networkfirewall_firewall('test', required_attrs)

        expect(ref.id).to eq("${aws_networkfirewall_firewall.test.id}")
        expect(ref.arn).to eq("${aws_networkfirewall_firewall.test.arn}")
        expect(ref.firewall_status).to eq("${aws_networkfirewall_firewall.test.firewall_status}")
        expect(ref.tags_all).to eq("${aws_networkfirewall_firewall.test.tags_all}")
        expect(ref.update_token).to eq("${aws_networkfirewall_firewall.test.update_token}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'test')
        expect(config).not_to have_key('arn')
        expect(config).not_to have_key('firewall_status')
        expect(config).not_to have_key('tags_all')
        expect(config).not_to have_key('update_token')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delete_protection: true, description: 'test-value', enabled_analysis_types: ['test-value'], encryption_configuration: [{ 'key1' => 'val1' }], firewall_policy_change_protection: true, subnet_change_protection: true, tags: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'full')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('enabled_analysis_types')
        expect(config).to have_key('encryption_configuration')
        expect(config).to have_key('firewall_policy_change_protection')
        expect(config).to have_key('subnet_change_protection')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enabled_analysis_types when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(enabled_analysis_types: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('enabled_analysis_types')
      end

      it 'omits enabled_analysis_types when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('enabled_analysis_types')
      end
      it 'includes encryption_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(encryption_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('encryption_configuration')
      end

      it 'omits encryption_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('encryption_configuration')
      end
      it 'includes firewall_policy_change_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(firewall_policy_change_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('firewall_policy_change_protection')
      end

      it 'omits firewall_policy_change_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('firewall_policy_change_protection')
      end
      it 'includes subnet_change_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(subnet_change_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('subnet_change_protection')
      end

      it 'omits subnet_change_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('subnet_change_protection')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('opt', required_attrs.merge(tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.aws_networkfirewall_firewall("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_networkfirewall_firewall', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts firewall_policy_change_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(firewall_policy_change_protection: val)
          synth.aws_networkfirewall_firewall("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_networkfirewall_firewall', "bool_#{val}")
          expect(config['firewall_policy_change_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts subnet_change_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(subnet_change_protection: val)
          synth.aws_networkfirewall_firewall("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'aws_networkfirewall_firewall', "bool_#{val}")
          expect(config['subnet_change_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_networkfirewall_firewall', 'typed')
        expect(config['firewall_policy_arn']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['subnet_mapping']).to be_a(Array)
        expect(config['vpc_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_networkfirewall_firewall('first', required_attrs)
        synth.aws_networkfirewall_firewall('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_networkfirewall_firewall')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_networkfirewall_firewall,
    method: :aws_networkfirewall_firewall,
    required_attrs: { firewall_policy_arn: 'test-value', name: 'test-value', subnet_mapping: [{ 'key1' => 'val1' }], vpc_id: 'test-value' },
    expected_outputs: [:id, :arn, :firewall_status, :tags_all, :update_token],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:delete_protection, :firewall_policy_change_protection, :subnet_change_protection]
end
