# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a aws_acmpca_permission resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::AWSAcmpcaPermission do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { actions: ['test-value'], certificate_authority_arn: 'test-value', principal: 'test-value' } }

  describe ':aws_acmpca_permission' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'aws_acmpca_permission', 'test')
        validate_required_attributes(config, [:actions, :certificate_authority_arn, :principal])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_acmpca_permission('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:aws_acmpca_permission)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.aws_acmpca_permission('test', required_attrs)

        expect(ref.id).to eq("${aws_acmpca_permission.test.id}")
        expect(ref.policy).to eq("${aws_acmpca_permission.test.policy}")
        expect(ref.region).to eq("${aws_acmpca_permission.test.region}")
        expect(ref.source_account).to eq("${aws_acmpca_permission.test.source_account}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_acmpca_permission', 'test')
        expect(config).not_to have_key('policy')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('source_account')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ region: 'test-value', source_account: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_acmpca_permission', 'full')
        expect(config).to have_key('region')
        expect(config).to have_key('source_account')
      end
    end

    context 'optional attributes' do
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_acmpca_permission', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_acmpca_permission', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes source_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('opt', required_attrs.merge(source_account: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_acmpca_permission', 'opt')
        expect(config).to have_key('source_account')
      end

      it 'omits source_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'aws_acmpca_permission', 'minimal')
        expect(config).not_to have_key('source_account')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'aws_acmpca_permission', 'typed')
        expect(config['actions']).to be_a(Array)
        expect(config['certificate_authority_arn']).to be_a(String)
        expect(config['principal']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.aws_acmpca_permission('first', required_attrs)
        synth.aws_acmpca_permission('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'aws_acmpca_permission')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :aws_acmpca_permission,
    method: :aws_acmpca_permission,
    required_attrs: { actions: ['test-value'], certificate_authority_arn: 'test-value', principal: 'test-value' },
    expected_outputs: [:id, :policy, :region, :source_account],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
