# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::AWS::Types
  include Dry.Types()

  class VpclatticeResourcePolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::AWS::Types

    attribute :policy, (T::String | T::Hash)
    attribute :resource_arn, T::String
    attribute? :region, T::String.optional
  end
end
